version: 0.2

env:
  variables:
    ENVIRONMENT: "dev"
    REGION: "us-east-1"
    FRONTEND_DOMAIN: "j-markets.jcampos.dev"
    ROOT_DOMAIN: "jcampos.dev"
    POS_LANDING_DOMAIN: "pos-landing.jcampos.dev"

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - cd templates/pos-landing && npm ci && cd ../..

  build:
    commands:
      - echo "Building pos-landing..."
      - cd templates/pos-landing && npm run build && cd ../..

  post_build:
    commands:
      - bash scripts/pipeline-frontend-pos-landing.sh

artifacts:
  files:
    - "**/*"
  base-directory: dist/templates/pos-landing
  discard-paths: no
