import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'es';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.success': 'Success',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.save': 'Save',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.back': 'Back',
    'common.next': 'Next',
    'common.submit': 'Submit',
    'common.or': 'or',
    'nav.features': 'Features',
    'nav.pricing': 'Pricing',
    'nav.examples': 'Examples',
    'nav.business': 'Business',
    'nav.about': 'About',
    'nav.contact': 'Contact',
    'nav.blog': 'Blog',
    'nav.login': 'Sign in',
    'nav.register': 'Get started free',
    'hero.badge': 'E-commerce platform',
    'hero.title': 'Your online store in minutes',
    'hero.subtitle': 'Create and manage your online store with all the tools you need to sell online.',
    'hero.cta': 'Create my store',
    'hero.secondary': 'View examples',
    'features.title': 'Everything you need',
    'features.subtitle': 'Powerful tools to grow your online business',
    'features.ecommerce.title': 'Complete e-commerce',
    'features.ecommerce.description': 'Shopping cart, checkout, inventory management and more',
    'features.payments.title': 'Secure payments',
    'features.payments.description': 'Integration with multiple payment gateways',
    'features.analytics.title': 'Analytics',
    'features.analytics.description': 'Detailed sales and behavior metrics',
    'features.customization.title': 'Customization',
    'features.customization.description': 'Customize colors, logos and styles',
    'features.inventory.title': 'Inventory',
    'features.inventory.description': 'Real-time stock control',
    'features.support.title': '24/7 Support',
    'features.support.description': 'Help when you need it',
    'pricing.title': 'Simple and transparent pricing',
    'pricing.subtitle': 'Choose the plan that best fits your business',
    'pricing.monthly': 'Monthly',
    'pricing.yearly': 'Yearly',
    'pricing.popular': 'Popular',
    'pricing.cta': 'Get started',
    'pricing.free.name': 'Free',
    'pricing.free.price': '$0',
    'pricing.free.description': 'To get started',
    'pricing.free.features.0': 'Up to 10 products',
    'pricing.free.features.1': '1 GB storage',
    'pricing.free.features.2': 'Email support',
    'pricing.free.features.3': 'jmarkets.dev domain',
    'pricing.pro.name': 'Pro',
    'pricing.pro.price': '$29',
    'pricing.pro.period': '/month',
    'pricing.pro.description': 'For growing businesses',
    'pricing.pro.features.0': 'Unlimited products',
    'pricing.pro.features.1': '10 GB storage',
    'pricing.pro.features.2': 'Priority support',
    'pricing.pro.features.3': 'Custom domain',
    'pricing.pro.features.4': 'Advanced analytics',
    'pricing.enterprise.name': 'Enterprise',
    'pricing.enterprise.price': 'Contact us',
    'pricing.enterprise.description': 'For large operations',
    'pricing.enterprise.features.0': 'Everything in Pro',
    'pricing.enterprise.features.1': 'Unlimited storage',
    'pricing.enterprise.features.2': 'Dedicated support',
    'pricing.enterprise.features.3': 'Custom API',
    'pricing.enterprise.features.4': 'Custom integrations',
    'examples.title': 'Get inspired by real stores',
    'examples.subtitle': 'Explore examples of stores created with JMarkets. Each one showcases different customizations and product categories.',
    'examples.badge': 'Example stores',
    'examples.featured': 'Featured',
    'examples.viewStore': 'View store',
    'examples.cta.title': 'Ready to create your own store?',
    'examples.cta.subtitle': 'Start free and customize your store however you want',
    'examples.cta.button': 'Create my store',
    'examples.stores.demo.title': 'JMarkets Demo',
    'examples.stores.demo.description': 'Complete example store with products, shopping cart, checkout and all platform features.',
    'examples.stores.demo.category': 'Demo',
    'examples.stores.bellaNatural.title': 'Tech Gadgets Pro',
    'examples.stores.bellaNatural.description': 'Latest electronics and tech accessories. Smartphones, laptops, tablets, and innovative gadgets for modern life.',
    'examples.stores.bellaNatural.category': 'Electronics',
    'examples.stores.glamStudio.title': 'Vintage Fashion Co',
    'examples.stores.glamStudio.description': 'Curated vintage and retro clothing collection. Unique pieces from decades past with timeless style.',
    'examples.stores.glamStudio.category': 'Fashion',
    'examples.stores.royalHair.title': 'Artisan Crafts Studio',
    'examples.stores.royalHair.description': 'Handmade crafts and DIY supplies. Knitting, painting, woodworking materials and unique handcrafted items.',
    'examples.stores.royalHair.category': 'Crafts',
    'examples.stores.skinLove.title': 'Gourmet Foods Market',
    'examples.stores.skinLove.description': 'Premium organic and specialty foods. Artisan cheeses, exotic spices, craft beverages and specialty products.',
    'examples.stores.skinLove.category': 'Food',
    'examples.stores.proNails.title': 'Fitness Equipment Hub',
    'examples.stores.proNails.description': 'Home and gym fitness equipment. Dumbbells, yoga mats, resistance bands and training accessories.',
    'examples.stores.proNails.category': 'Sports',
    'examples.stores.beautySalon.title': 'Pet Care Supplies',
    'examples.stores.beautySalon.description': 'Everything for your pets. Pet toys, grooming products, nutrition, and comfortable beds for cats and dogs.',
    'examples.stores.beautySalon.category': 'Pets',
    'footer.description': 'Complete e-commerce platform for small businesses and entrepreneurs',
    'footer.product': 'Product',
    'footer.company': 'Company',
    'footer.legal': 'Legal',
    'footer.links.features': 'Features',
    'footer.links.pricing': 'Pricing',
    'footer.links.examples': 'Examples',
    'footer.links.about': 'About us',
    'footer.links.contact': 'Contact',
    'footer.links.blog': 'Blog',
    'footer.links.privacy': 'Privacy',
    'footer.links.terms': 'Terms',
    'footer.links.cookies': 'Cookies',
    'footer.copyright': '© 2024 JMarkets. All rights reserved.',
    'auth.login.title': 'JMarkets',
    'auth.login.subtitle': 'Sign in to your account',
    'auth.login.email': 'Email',
    'auth.login.emailPlaceholder': 'your@email.com',
    'auth.login.password': 'Password',
    'auth.login.passwordPlaceholder': 'Enter your password',
    'auth.login.submit': 'Sign in',
    'auth.login.submitting': 'Signing in...',
    'auth.login.forgotPassword': 'Forgot your password?',
    'auth.login.noAccount': "Don't have an account?",
    'auth.login.register': 'Register',
    'auth.login.backToHome': 'Back to home',
    'auth.login.success': 'Login successful',
    'auth.login.successDescription': 'Welcome back',
    'auth.login.error': 'Login error',
    'auth.register.title': 'Create account',
    'auth.register.subtitle': 'Start creating your store today',
    'auth.register.steps.personalInfo': 'Personal Info',
    'auth.register.steps.personalInfoDesc': 'Your basic information',
    'auth.register.steps.security': 'Security',
    'auth.register.steps.securityDesc': 'Create your password',
    'auth.register.steps.verify': 'Verify',
    'auth.register.steps.verifyDesc': 'Confirm your email',
    'auth.register.firstName': 'First name',
    'auth.register.firstNamePlaceholder': 'Your name',
    'auth.register.lastName': 'Last name',
    'auth.register.lastNamePlaceholder': 'Your last name',
    'auth.register.email': 'Email',
    'auth.register.emailPlaceholder': 'your@email.com',
    'auth.register.gender': 'Gender (optional)',
    'auth.register.gender.placeholder': 'Select your gender...',
    'auth.register.gender.male': 'Male',
    'auth.register.gender.female': 'Female',
    'auth.register.gender.other': 'Other',
    'auth.register.gender.otherPlaceholder': 'Please specify...',
    'auth.register.gender.preferNotToSay': 'Prefer not to say',
    'auth.register.password': 'Password',
    'auth.register.passwordPlaceholder': 'Create a password',
    'auth.register.confirmPassword': 'Confirm password',
    'auth.register.confirmPasswordPlaceholder': 'Confirm your password',
    'auth.register.continue': 'Continue',
    'auth.register.back': 'Back',
    'auth.register.createAccount': 'Create account',
    'auth.register.submit': 'Create account',
    'auth.register.submitting': 'Creating account...',
    'auth.register.hasAccount': 'Already have an account?',
    'auth.register.signIn': 'Sign in',
    'auth.register.login': 'Sign in',
    'auth.register.backToHome': 'Back to home',
    'auth.register.success': 'Account created',
    'auth.register.successDescription': 'Check your email to verify your account',
    'auth.register.complete': 'Registration complete',
    'auth.register.completeDescription': 'Your account is ready to use',
    'auth.register.completeStep1': 'Please complete step 1 first',
    'auth.register.error': 'Error creating account',
    'auth.register.passwordMismatch': 'Passwords do not match',
    'auth.register.passwordRequirements.minLength': 'Minimum 8 characters',
    'auth.register.passwordRequirements.lowercase': 'One lowercase letter',
    'auth.register.passwordRequirements.uppercase': 'One uppercase letter',
    'auth.register.passwordRequirements.number': 'One number',
    'auth.register.passwordRequirements.special': 'One special character',
    'auth.register.passwordStrength.label': 'Password Strength',
    'auth.register.passwordStrength.weak': 'Weak',
    'auth.register.passwordStrength.fair': 'Fair',
    'auth.register.passwordStrength.good': 'Good',
    'auth.register.passwordStrength.strong': 'Strong',
    'auth.register.passwordStrength.excellent': 'Excellent',
    'auth.forgotPassword.title': 'Forgot your password?',
    'auth.forgotPassword.subtitle': "Enter your email and we'll send you a recovery code",
    'auth.forgotPassword.email': 'Email',
    'auth.forgotPassword.emailPlaceholder': 'your@email.com',
    'auth.forgotPassword.submit': 'Send code',
    'auth.forgotPassword.submitting': 'Sending...',
    'auth.forgotPassword.backToLogin': 'Back to sign in',
    'auth.forgotPassword.success': 'Code sent',
    'auth.forgotPassword.successDescription': 'Check your email for the recovery code',
    'auth.forgotPassword.error': 'Error sending code',
    'auth.forgotPassword.checkEmail.title': 'Check your email',
    'auth.forgotPassword.checkEmail.subtitle': "We've sent a recovery code to",
    'auth.forgotPassword.checkEmail.enterCode': 'Enter code',
    'auth.forgotPassword.checkEmail.differentEmail': 'Use different email',
    'auth.resetPassword.title': 'Reset password',
    'auth.resetPassword.subtitle': 'Enter the code from your email and your new password',
    'auth.resetPassword.email': 'Email',
    'auth.resetPassword.emailPlaceholder': 'your@email.com',
    'auth.resetPassword.code': 'Recovery code',
    'auth.resetPassword.codePlaceholder': 'Enter 6-digit code',
    'auth.resetPassword.newPassword': 'New password',
    'auth.resetPassword.newPasswordPlaceholder': 'Enter your new password',
    'auth.resetPassword.confirmPassword': 'Confirm password',
    'auth.resetPassword.confirmPasswordPlaceholder': 'Confirm your new password',
    'auth.resetPassword.submit': 'Reset password',
    'auth.resetPassword.submitting': 'Resetting...',
    'auth.resetPassword.requestNewCode': 'Request new code',
    'auth.resetPassword.backToHome': 'Back to home',
    'auth.resetPassword.success': 'Password reset',
    'auth.resetPassword.successDescription': 'You can now sign in with your new password',
    'auth.resetPassword.error': 'Error resetting password',
    'auth.resetPassword.invalidCode': 'Invalid code',
    'auth.resetPassword.invalidCodeDescription': 'The code you entered is incorrect',
    'auth.resetPassword.expiredCode': 'Code expired',
    'auth.resetPassword.expiredCodeDescription': 'Please request a new code',
    'auth.verifyEmail.title': 'Verify your email',
    'auth.verifyEmail.subtitle': 'Enter the verification code sent to',
    'auth.verifyEmail.code': 'Verification code',
    'auth.verifyEmail.submit': 'Verify',
    'auth.verifyEmail.submitting': 'Verifying...',
    'auth.verifyEmail.resendCode': 'Resend code',
    'auth.verifyEmail.resending': 'Resending...',
    'auth.verifyEmail.didntReceive': "Didn't receive the code?",
    'auth.verifyEmail.success': 'Email verified',
    'auth.verifyEmail.successDescription': 'Your account has been successfully verified',
    'auth.verifyEmail.error': 'Verification error',
    'auth.verifyEmail.resendSuccess': 'Code resent',
    'auth.verifyEmail.resendSuccessDescription': 'Check your email for the new code',
    'organizations.create.title': 'Create your organization',
    'organizations.create.subtitle': 'Set up your store in minutes',
    'organizations.create.name': 'Store name',
    'organizations.create.namePlaceholder': 'My Store',
    'organizations.create.nameDescription': 'The public name of your store',
    'organizations.create.slug': 'Store URL',
    'organizations.create.slugPlaceholder': 'my-store',
    'organizations.create.slugDescription': 'The unique URL of your store',
    'organizations.create.subdomain': 'Subdomain',
    'organizations.create.subdomainDescription': 'Your store will be available at',
    'organizations.create.submit': 'Create store',
    'organizations.create.submitting': 'Creating store...',
    'organizations.create.success': 'Store created',
    'organizations.create.successDescription': 'Your store is ready',
    'organizations.create.error': 'Error creating store',
    'organizations.create.slugTaken': 'This URL is already in use',
    'organizations.create.subdomainTaken': 'This subdomain is already in use',
    'organizations.create.checking': 'Checking availability...',
    'organizations.select.title': 'Select your organization',
    'organizations.select.subtitle': 'Choose the store you want to manage',
    'organizations.select.createNew': 'Create new store',
    'organizations.select.noOrganizations': 'You have no organizations',
    'organizations.select.noOrganizationsDescription': 'Create your first store to get started',
    'organizations.select.loading': 'Loading organizations...',
    'organizations.select.visitStore': 'Visit store',
    'organizations.select.manage': 'Manage',
    'theme.light': 'Light',
    'theme.dark': 'Dark',
    'theme.system': 'System',
    'language.es': 'Español',
    'language.en': 'English',
    'about.badge': 'About us',
    'about.title': 'Building the future of e-commerce',
    'about.subtitle': 'We help entrepreneurs and small businesses succeed online',
    'about.mission.title': 'Our Mission',
    'about.mission.description': 'To empower small businesses and entrepreneurs by providing an affordable, easy-to-use platform to create and manage their online stores.',
    'about.values.title': 'Our Values',
    'about.values.innovation': 'Innovation',
    'about.values.innovation.description': 'We constantly improve and adapt to new technologies and market needs',
    'about.values.accessibility': 'Accessibility',
    'about.values.accessibility.description': 'Everyone should have access to e-commerce tools, regardless of technical skill',
    'about.values.support': 'Support',
    'about.values.support.description': 'Your success is our success. We provide dedicated customer support',
    'about.values.security': 'Security',
    'about.values.security.description': 'Your data and your customers\' data are protected with enterprise-grade security',
    'blog.badge': 'Blog',
    'blog.title': 'Latest news and updates',
    'blog.subtitle': 'Tips, guides, and insights for growing your online business',
    'blog.featured': 'Featured Article',
    'blog.readMore': 'Read More',
    'blog.posted': 'Posted',
    'contact.badge': 'Contact Us',
    'contact.title': 'Get in touch',
    'contact.subtitle': 'We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
    'contact.form.name': 'Full Name',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Subject',
    'contact.form.message': 'Message',
    'contact.form.submit': 'Send Message',
    'contact.form.sending': 'Sending...',
    'contact.form.success': 'Message sent successfully!',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Phone',
    'contact.info.address': 'Address',
    'terms.badge': 'Terms of Service',
    'terms.title': 'Terms and Conditions',
    'terms.subtitle': 'Please read these terms carefully before using our platform',
    'terms.lastUpdated': 'Last updated',
    'terms.section.acceptance': '1. Acceptance of Terms',
    'terms.section.accounts': '2. User Accounts',
    'terms.section.services': '3. Services Description',
    'terms.section.payment': '4. Payment Terms',
    'terms.section.intellectual': '5. Intellectual Property',
    'terms.section.liability': '6. Limitation of Liability',
    'terms.section.changes': '7. Changes to Terms',
    'terms.section.contact': '8. Contact Information',
    'privacy.badge': 'Privacy Policy',
    'privacy.title': 'Privacy Policy',
    'privacy.subtitle': 'How we collect, use, and protect your information',
    'privacy.lastUpdated': 'Last updated',
    'privacy.section.information': '1. Information We Collect',
    'privacy.section.usage': '2. How We Use Your Information',
    'privacy.section.storage': '3. Data Storage and Security',
    'privacy.section.cookies': '4. Cookies and Tracking',
    'privacy.section.third': '5. Third-Party Services',
    'privacy.section.rights': '6. Your Rights',
    'privacy.section.protection': '7. Data Protection',
    'privacy.section.contact': '8. Contact Information',
    'cookies.badge': 'Cookie Policy',
    'cookies.title': 'Cookie Policy',
    'cookies.subtitle': 'Information about how we use cookies',
    'cookies.what': 'What are Cookies?',
    'cookies.types': 'Types of Cookies',
    'cookies.essential': 'Essential Cookies',
    'cookies.essential.description': 'Necessary for basic functionality',
    'cookies.analytics': 'Analytics Cookies',
    'cookies.analytics.description': 'Help us understand how you use our platform',
    'cookies.marketing': 'Marketing Cookies',
    'cookies.marketing.description': 'Used to personalize content and ads',
    'cookies.preferences': 'Preference Cookies',
    'cookies.preferences.description': 'Remember your choices and settings',
    'cookies.manage': 'Manage Cookie Preferences',
    'cookies.explanation': 'Cookies are small text files that are stored on your device when you visit a website. They help websites remember information about your visit, such as your preferences and activity. Cookies can be essential for basic website functionality or used to enhance user experience through tracking and personalization.',
    'cookies.browser': 'Most web browsers allow you to control cookies through their settings. You can choose to accept all cookies, reject all cookies, or be notified when a cookie is being set.',
    'cookies.usingBrowser': 'Using Your Browser',
    'cookies.usingBrowserDesc': 'Most modern browsers include cookie management tools in their settings. You can typically find these under "Privacy" or "Security" settings. Different browsers (Chrome, Firefox, Safari, Edge) have different processes, but all allow you to view, delete, and manage cookies.',
    'cookies.consent': 'Cookie Consent',
    'cookies.consentDesc': 'When you first visit JMarkets, we display a cookie consent banner. You can accept all cookies, reject non-essential cookies, or customize your preferences. You can change your cookie preferences at any time through your account settings.',
    'cookies.third': 'Third-Party Cookies',
    'cookies.thirdDesc': 'Some cookies may be set by third-party services (like analytics providers). These services have their own privacy policies and cookie management options. You can often manage these preferences through the third-party\'s website.',
    'cookies.important': 'Important Note',
    'cookies.importantDesc': 'Disabling essential cookies may affect the functionality of our platform. We recommend keeping essential cookies enabled to ensure the best experience. Non-essential cookies can be disabled without affecting core functionality.',
    'terms.acceptance.content': 'By accessing and using this platform, you accept and agree to be bound by the terms and provision of this agreement. If you do not agree to abide by the above, please do not use this service.',
    'terms.accounts.content': 'You are responsible for maintaining the confidentiality of your account information and password and for restricting access to your computer. You agree to accept responsibility for all activities that occur under your account or password.',
    'terms.services.content': 'JMarkets provides a platform for creating and managing online stores. We strive to provide accurate and helpful information, but we cannot guarantee the accuracy or completeness of all information on the platform.',
    'terms.payment.content': 'Payment terms are agreed upon at the time of purchase. All fees are exclusive of applicable taxes unless stated otherwise. Refunds, if applicable, will be processed according to the specific plan terms.',
    'terms.intellectual.content': 'All content included on this site, such as text, graphics, logos, images, audio clips, and software, is the property of JMarkets or its content suppliers and protected by international copyright laws.',
    'terms.liability.content': 'This platform is provided on an "as is" basis. JMarkets makes no warranties, expressed or implied, and hereby disclaims and negates all other warranties including, without limitation, implied warranties or conditions of merchantability, fitness for a particular purpose, or non-infringement of intellectual property or other violation of rights.',
    'terms.changes.content': 'JMarkets reserves the right to change the terms and conditions of this agreement at any time. Users will be notified of any changes via email or prominent notice on the platform.',
    'terms.contact.content': 'If you have any questions about these terms and conditions, please contact us at support@jmarkets.com or visit our contact page.',
    'terms.lastUpdatedDate': 'January 1, 2024',
    'terms.importantNotice': 'Important Notice',
    'terms.acceptanceNotice': 'By using JMarkets, you acknowledge that you have read, understood, and agree to be bound by all the terms and conditions outlined in this document. If you do not agree with any part of these terms, please discontinue use of our platform.',
    'privacy.information.content': 'We collect information you provide directly to us, such as when you create an account, make a purchase, or contact us. This includes your name, email address, password, and payment information. We also collect information automatically when you use our platform, including log data, cookies, and device information.',
    'privacy.usage.content': 'We use your information to provide, maintain, and improve our services, process transactions, send transactional and promotional emails, respond to your inquiries, and comply with legal obligations. We use analytics data to understand how users interact with our platform and to optimize the user experience.',
    'privacy.storage.content': 'Your data is stored on secure servers with encryption technology. We implement appropriate physical, electronic, and procedural safeguards to protect your information against unauthorized access, alteration, disclosure, or destruction. However, no method of transmission over the Internet is completely secure.',
    'privacy.cookies.content': 'We use cookies and similar tracking technologies to track activity on our platform and hold certain information. You can instruct your browser to refuse all cookies or to alert you when cookies are being sent. However, some features of the platform may not function properly without cookies.',
    'privacy.third.content': 'We may share your information with third-party service providers who assist us in operating our platform and conducting our business. These providers are contractually obligated to use your information only as necessary to provide services to us.',
    'privacy.rights.content': 'Depending on your location, you may have certain rights regarding your personal data, including the right to access, correct, delete, or port your information. To exercise any of these rights, please contact us at privacy@jmarkets.com.',
    'privacy.protection.content': 'We comply with applicable data protection regulations, including GDPR and similar laws. We maintain appropriate safeguards to protect your data and only retain information for as long as necessary to provide our services and comply with legal obligations.',
    'privacy.contact.content': 'If you have questions about this privacy policy or our privacy practices, please contact us at privacy@jmarkets.com or visit our contact page. We are committed to working with you to resolve any privacy concerns.',
    'privacy.lastUpdatedDate': 'January 1, 2024',
    'privacy.notice': 'Your Privacy Matters',
    'privacy.noticeDesc': 'We are committed to protecting your privacy and ensuring you have a positive experience on our platform. If you have any questions about how we handle your data, please don\'t hesitate to contact us.',
    'contact.sendMessage': 'Send us a message',
    'contact.namePlaceholder': 'John Doe',
    'contact.emailPlaceholder': 'john@example.com',
    'contact.subjectPlaceholder': 'How can we help?',
    'contact.messagePlaceholder': 'Your message here...',
    'contact.tryAgain': 'Please try again.',
    'contact.otherWays': 'Other ways to reach us',
    'contact.responseTime': 'Response Time',
    'contact.responseTimeDesc': 'We typically respond to all inquiries within 24 hours during business days. Thank you for your patience!',
    'about.ourStory': 'Our Story',
    'about.storyPara1': 'JMarkets was founded with a simple vision: to democratize e-commerce and make it accessible to everyone. We recognized that many talented entrepreneurs and small business owners lacked the technical skills or financial resources to create and manage professional online stores.',
    'about.storyPara2': 'What started as a small project has grown into a comprehensive platform trusted by thousands of businesses worldwide. We\'ve continuously evolved our offerings based on feedback from our users, always keeping their success at the forefront of everything we do.',
    'about.storyPara3': 'Today, JMarkets stands as a testament to the power of entrepreneurship and community. We\'re proud to support businesses of all sizes in achieving their online growth goals, and we remain committed to innovation, security, and customer success.',
    'about.stats.stores': 'Active Stores',
    'about.stats.storesNumber': '5,000+',
    'about.stats.countries': 'Countries',
    'about.stats.countriesNumber': '50+',
    'about.stats.transactions': 'Transactions Processed',
    'about.stats.transactionsNumber': '$100M+',
    'about.teamHeading': 'Dedicated to Your Success',
    'about.teamDesc': 'Our team is comprised of passionate professionals with backgrounds in technology, business, and customer support. We\'re united by a common goal: to empower entrepreneurs and help them succeed in the digital marketplace. Whether you need technical assistance, business advice, or just encouragement, our team is here for you.',
    'blog.latestArticles': 'Latest Articles',
    'blog.stayUpdated': 'Stay Updated',
    'blog.newsletter': 'Subscribe to our newsletter and get the latest articles, tips, and updates delivered to your inbox.',
    'blog.subscribe': 'Subscribe',
    'blog.privacyNote': 'We respect your privacy. Unsubscribe at any time.',
    'blog.article1.title': 'Getting Started with Your Online Store',
    'blog.article1.excerpt': 'Learn the basics of setting up your first e-commerce store and optimizing it for success.',
    'blog.article1.author': 'Sarah Johnson',
    'blog.article1.date': 'January 15, 2024',
    'blog.article2.title': '10 Tips to Increase Your Online Sales',
    'blog.article2.excerpt': 'Proven strategies to boost conversions and grow your business revenue.',
    'blog.article2.author': 'Michael Chen',
    'blog.article2.date': 'January 10, 2024',
    'blog.article3.title': 'Understanding Your Customer Analytics',
    'blog.article3.excerpt': 'How to interpret analytics data to make better business decisions.',
    'blog.article3.author': 'Emma Rodriguez',
    'blog.article3.date': 'January 5, 2024',
    'blog.article4.title': 'Payment Gateway Security: What You Need to Know',
    'blog.article4.excerpt': 'A comprehensive guide to securing your customer payment information.',
    'blog.article4.author': 'James Wilson',
    'blog.article4.date': 'December 28, 2023',
    'blog.article5.title': 'Inventory Management Best Practices',
    'blog.article5.excerpt': 'Optimize your inventory to reduce costs and improve customer satisfaction.',
    'blog.article5.author': 'Lisa Anderson',
    'blog.article5.date': 'December 20, 2023',
    'blog.article6.title': 'Email Marketing Strategies for E-commerce',
    'blog.article6.excerpt': 'Build customer loyalty through effective email campaigns.',
    'blog.article6.author': 'David Martinez',
    'blog.article6.date': 'December 12, 2023',
  },
  es: {
    'common.loading': 'Cargando...',
    'common.error': 'Error',
    'common.success': 'Éxito',
    'common.cancel': 'Cancelar',
    'common.confirm': 'Confirmar',
    'common.save': 'Guardar',
    'common.delete': 'Eliminar',
    'common.edit': 'Editar',
    'common.back': 'Volver',
    'common.next': 'Siguiente',
    'common.submit': 'Enviar',
    'common.or': 'o',
    'nav.features': 'Características',
    'nav.pricing': 'Precios',
    'nav.examples': 'Ejemplos',
    'nav.business': 'Empresa',
    'nav.about': 'Nosotros',
    'nav.contact': 'Contacto',
    'nav.blog': 'Blog',
    'nav.login': 'Iniciar sesión',
    'nav.register': 'Comenzar gratis',
    'hero.badge': 'Plataforma de e-commerce',
    'hero.title': 'Tu tienda online en minutos',
    'hero.subtitle': 'Crea y gestiona tu tienda online con todas las herramientas que necesitas para vender en línea.',
    'hero.cta': 'Crear mi tienda',
    'hero.secondary': 'Ver ejemplos',
    'features.title': 'Todo lo que necesitas',
    'features.subtitle': 'Herramientas poderosas para hacer crecer tu negocio online',
    'features.ecommerce.title': 'E-commerce completo',
    'features.ecommerce.description': 'Carrito de compras, checkout, gestión de inventario y más',
    'features.payments.title': 'Pagos seguros',
    'features.payments.description': 'Integración con múltiples pasarelas de pago',
    'features.analytics.title': 'Analíticas',
    'features.analytics.description': 'Métricas detalladas de ventas y comportamiento',
    'features.customization.title': 'Personalización',
    'features.customization.description': 'Personaliza colores, logos y estilos',
    'features.inventory.title': 'Inventario',
    'features.inventory.description': 'Control de stock en tiempo real',
    'features.support.title': 'Soporte 24/7',
    'features.support.description': 'Ayuda cuando la necesites',
    'pricing.title': 'Precios simples y transparentes',
    'pricing.subtitle': 'Elige el plan que mejor se adapte a tu negocio',
    'pricing.monthly': 'Mensual',
    'pricing.yearly': 'Anual',
    'pricing.popular': 'Popular',
    'pricing.cta': 'Comenzar',
    'pricing.free.name': 'Gratis',
    'pricing.free.price': '$0',
    'pricing.free.description': 'Para empezar',
    'pricing.free.features.0': 'Hasta 10 productos',
    'pricing.free.features.1': '1 GB de almacenamiento',
    'pricing.free.features.2': 'Soporte por email',
    'pricing.free.features.3': 'Dominio jmarkets.dev',
    'pricing.pro.name': 'Pro',
    'pricing.pro.price': '$29',
    'pricing.pro.period': '/mes',
    'pricing.pro.description': 'Para negocios en crecimiento',
    'pricing.pro.features.0': 'Productos ilimitados',
    'pricing.pro.features.1': '10 GB de almacenamiento',
    'pricing.pro.features.2': 'Soporte prioritario',
    'pricing.pro.features.3': 'Dominio personalizado',
    'pricing.pro.features.4': 'Analíticas avanzadas',
    'pricing.enterprise.name': 'Empresa',
    'pricing.enterprise.price': 'Contactar',
    'pricing.enterprise.description': 'Para grandes operaciones',
    'pricing.enterprise.features.0': 'Todo en Pro',
    'pricing.enterprise.features.1': 'Almacenamiento ilimitado',
    'pricing.enterprise.features.2': 'Soporte dedicado',
    'pricing.enterprise.features.3': 'API personalizada',
    'pricing.enterprise.features.4': 'Integraciones custom',
    'examples.title': 'Inspírate con tiendas reales',
    'examples.subtitle': 'Explora ejemplos de tiendas creadas con JMarkets. Cada una muestra diferentes personalizaciones y categorías de productos.',
    'examples.badge': 'Tiendas de ejemplo',
    'examples.featured': 'Destacada',
    'examples.viewStore': 'Ver tienda',
    'examples.cta.title': 'Comienza a crear tu propia tienda',
    'examples.cta.subtitle': 'Comienza gratis y personaliza tu tienda como quieras',
    'examples.cta.button': 'Crear mi tienda',
    'examples.stores.demo.title': 'JMarkets Demo',
    'examples.stores.demo.description': 'Tienda de ejemplo completa con productos, carrito de compras, checkout y todas las funcionalidades de la plataforma.',
    'examples.stores.demo.category': 'Demo',
    'examples.stores.bellaNatural.title': 'Tech Gadgets Pro',
    'examples.stores.bellaNatural.description': 'Últimos gadgets y accesorios electrónicos. Smartphones, laptops, tablets y dispositivos innovadores para la vida moderna.',
    'examples.stores.bellaNatural.category': 'Electrónica',
    'examples.stores.glamStudio.title': 'Vintage Fashion Co',
    'examples.stores.glamStudio.description': 'Colección curada de ropa vintage y retro. Piezas únicas de décadas pasadas con estilo atemporal.',
    'examples.stores.glamStudio.category': 'Moda',
    'examples.stores.royalHair.title': 'Artisan Crafts Studio',
    'examples.stores.royalHair.description': 'Manualidades y suministros para DIY. Materiales para tejer, pintar, trabajar la madera y artículos únicos hechos a mano.',
    'examples.stores.royalHair.category': 'Artesanías',
    'examples.stores.skinLove.title': 'Gourmet Foods Market',
    'examples.stores.skinLove.description': 'Alimentos orgánicos y especiales premium. Quesos artesanales, especias exóticas, bebidas artesanales y productos especiales.',
    'examples.stores.skinLove.category': 'Alimentos',
    'examples.stores.proNails.title': 'Fitness Equipment Hub',
    'examples.stores.proNails.description': 'Equipamiento de fitness para hogar y gimnasio. Mancuernas, tapetes de yoga, bandas de resistencia y accesorios de entrenamiento.',
    'examples.stores.proNails.category': 'Deportes',
    'examples.stores.beautySalon.title': 'Pet Care Supplies',
    'examples.stores.beautySalon.description': 'Todo para tus mascotas. Juguetes, productos de aseo, nutrición y camas cómodas para gatos y perros.',
    'examples.stores.beautySalon.category': 'Mascotas',
    'footer.description': 'Plataforma de e-commerce completa para negocios y emprendedores',
    'footer.product': 'Producto',
    'footer.company': 'Empresa',
    'footer.legal': 'Legal',
    'footer.links.features': 'Características',
    'footer.links.pricing': 'Precios',
    'footer.links.examples': 'Ejemplos',
    'footer.links.about': 'Nosotros',
    'footer.links.contact': 'Contacto',
    'footer.links.blog': 'Blog',
    'footer.links.privacy': 'Privacidad',
    'footer.links.terms': 'Términos',
    'footer.links.cookies': 'Cookies',
    'footer.copyright': '© 2024 JMarkets. Todos los derechos reservados.',
    'about.badge': 'Nosotros',
    'about.title': 'Construyendo el futuro del e-commerce',
    'about.subtitle': 'Ayudamos a emprendedores y pequeños negocios a triunfar en línea',
    'about.mission.title': 'Nuestra Misión',
    'about.mission.description': 'Empoderar a pequeños negocios y emprendedores proporcionando una plataforma asequible y fácil de usar para crear y gestionar sus tiendas en línea.',
    'about.values.title': 'Nuestros Valores',
    'about.values.innovation': 'Innovación',
    'about.values.innovation.description': 'Mejoramos continuamente y nos adaptamos a nuevas tecnologías y necesidades del mercado',
    'about.values.accessibility': 'Accesibilidad',
    'about.values.accessibility.description': 'Todos deben tener acceso a herramientas de e-commerce, independientemente de su habilidad técnica',
    'about.values.support': 'Soporte',
    'about.values.support.description': 'Tu éxito es nuestro éxito. Proporcionamos soporte dedicado al cliente',
    'about.values.security': 'Seguridad',
    'about.values.security.description': 'Tus datos y los datos de tus clientes están protegidos con seguridad de nivel empresarial',
    'blog.badge': 'Blog',
    'blog.title': 'Últimas noticias y actualizaciones',
    'blog.subtitle': 'Consejos, guías e información para hacer crecer tu negocio en línea',
    'blog.featured': 'Artículo Destacado',
    'blog.readMore': 'Leer Más',
    'blog.posted': 'Publicado',
    'contact.badge': 'Contacto',
    'contact.title': 'Ponte en contacto',
    'contact.subtitle': 'Nos encantaría escucharte. Envíanos un mensaje y te responderemos lo antes posible.',
    'contact.form.name': 'Nombre Completo',
    'contact.form.email': 'Email',
    'contact.form.subject': 'Asunto',
    'contact.form.message': 'Mensaje',
    'contact.form.submit': 'Enviar Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.success': '¡Mensaje enviado exitosamente!',
    'contact.info.email': 'Email',
    'contact.info.phone': 'Teléfono',
    'contact.info.address': 'Dirección',
    'terms.badge': 'Términos de Servicio',
    'terms.title': 'Términos y Condiciones',
    'terms.subtitle': 'Por favor, lee estos términos cuidadosamente antes de usar nuestra plataforma',
    'terms.lastUpdated': 'Última actualización',
    'terms.section.acceptance': '1. Aceptación de Términos',
    'terms.section.accounts': '2. Cuentas de Usuario',
    'terms.section.services': '3. Descripción de Servicios',
    'terms.section.payment': '4. Términos de Pago',
    'terms.section.intellectual': '5. Propiedad Intelectual',
    'terms.section.liability': '6. Limitación de Responsabilidad',
    'terms.section.changes': '7. Cambios en los Términos',
    'terms.section.contact': '8. Información de Contacto',
    'privacy.badge': 'Política de Privacidad',
    'privacy.title': 'Política de Privacidad',
    'privacy.subtitle': 'Cómo recopilamos, usamos y protegemos tu información',
    'privacy.lastUpdated': 'Última actualización',
    'privacy.section.information': '1. Información que Recopilamos',
    'privacy.section.usage': '2. Cómo Usamos tu Información',
    'privacy.section.storage': '3. Almacenamiento y Seguridad de Datos',
    'privacy.section.cookies': '4. Cookies y Seguimiento',
    'privacy.section.third': '5. Servicios de Terceros',
    'privacy.section.rights': '6. Tus Derechos',
    'privacy.section.protection': '7. Protección de Datos',
    'privacy.section.contact': '8. Información de Contacto',
    'cookies.badge': 'Política de Cookies',
    'cookies.title': 'Política de Cookies',
    'cookies.subtitle': 'Información sobre cómo utilizamos las cookies',
    'cookies.what': '¿Qué son las Cookies?',
    'cookies.types': 'Tipos de Cookies',
    'cookies.essential': 'Cookies Esenciales',
    'cookies.essential.description': 'Necesarias para la funcionalidad básica',
    'cookies.analytics': 'Cookies de Análisis',
    'cookies.analytics.description': 'Nos ayudan a entender cómo usas nuestra plataforma',
    'cookies.marketing': 'Cookies de Marketing',
    'cookies.marketing.description': 'Se utilizan para personalizar contenido y anuncios',
    'cookies.preferences': 'Cookies de Preferencia',
    'cookies.preferences.description': 'Recuerdan tus opciones y configuración',
    'cookies.manage': 'Gestionar Preferencias de Cookies',
    'cookies.explanation': 'Las cookies son pequeños archivos de texto que se almacenan en tu dispositivo cuando visitas un sitio web. Ayudan a los sitios web a recordar información sobre tu visita, como tus preferencias y actividad. Las cookies pueden ser esenciales para la funcionalidad básica del sitio web o se pueden usar para mejorar la experiencia del usuario a través del seguimiento y personalización.',
    'cookies.browser': 'La mayoría de navegadores web te permiten controlar las cookies a través de su configuración. Puedes elegir aceptar todas las cookies, rechazar todas o ser notificado cuando se establezca una cookie.',
    'cookies.usingBrowser': 'Usando tu Navegador',
    'cookies.usingBrowserDesc': 'La mayoría de navegadores modernos incluyen herramientas de gestión de cookies en su configuración. Generalmente puedes encontrarlas bajo "Privacidad" o configuración de "Seguridad". Diferentes navegadores (Chrome, Firefox, Safari, Edge) tienen diferentes procesos, pero todos te permiten ver, eliminar y gestionar cookies.',
    'cookies.consent': 'Consentimiento de Cookies',
    'cookies.consentDesc': 'Cuando visitas JMarkets por primera vez, mostramos un banner de consentimiento de cookies. Puedes aceptar todas las cookies, rechazar las no esenciales o personalizar tus preferencias. Puedes cambiar tus preferencias de cookies en cualquier momento a través de la configuración de tu cuenta.',
    'cookies.third': 'Cookies de Terceros',
    'cookies.thirdDesc': 'Algunas cookies pueden ser establecidas por servicios de terceros (como proveedores de análisis). Estos servicios tienen sus propias políticas de privacidad y opciones de gestión de cookies. A menudo puedes gestionar estas preferencias a través del sitio web del tercero.',
    'cookies.important': 'Nota Importante',
    'cookies.importantDesc': 'Deshabilitar las cookies esenciales puede afectar la funcionalidad de nuestra plataforma. Recomendamos mantener las cookies esenciales habilitadas para garantizar la mejor experiencia. Las cookies no esenciales se pueden deshabilitar sin afectar la funcionalidad principal.',
    'terms.acceptance.content': 'Al acceder y utilizar esta plataforma, aceptas y estás de acuerdo en estar vinculado por los términos y disposiciones de este acuerdo. Si no estás de acuerdo en cumplir lo anterior, por favor no uses este servicio.',
    'terms.accounts.content': 'Eres responsable de mantener la confidencialidad de tu información de cuenta y contraseña, y de restringir el acceso a tu computadora. Aceptas asumir la responsabilidad de todas las actividades que ocurran bajo tu cuenta o contraseña.',
    'terms.services.content': 'JMarkets proporciona una plataforma para crear y gestionar tiendas en línea. Nos esforzamos por proporcionar información precisa y útil, pero no podemos garantizar la precisión o integridad de toda la información en la plataforma.',
    'terms.payment.content': 'Los términos de pago se acuerdan en el momento de la compra. Todas las tarifas son exclusivas de impuestos aplicables a menos que se indique lo contrario. Los reembolsos, si corresponde, se procesarán de acuerdo con los términos del plan específico.',
    'terms.intellectual.content': 'Todo el contenido incluido en este sitio, como texto, gráficos, logotipos, imágenes, clips de audio y software, es propiedad de JMarkets o sus proveedores de contenido y está protegido por leyes internacionales de derechos de autor.',
    'terms.liability.content': 'Esta plataforma se proporciona tal cual. JMarkets no ofrece garantías, expresas o implícitas, y rechaza todas las demás garantías, incluyendo, sin limitación, garantías implícitas o condiciones de comerciabilidad, aptitud para un propósito particular o no infracción de la propiedad intelectual u otra violación de derechos.',
    'terms.changes.content': 'JMarkets se reserva el derecho de cambiar los términos y condiciones de este acuerdo en cualquier momento. Los usuarios serán notificados de cualquier cambio por correo electrónico o aviso destacado en la plataforma.',
    'terms.contact.content': 'Si tienes preguntas sobre estos términos y condiciones, contáctanos en support@jmarkets.com o visita nuestra página de contacto.',
    'terms.lastUpdatedDate': '1 de enero de 2024',
    'terms.importantNotice': 'Aviso Importante',
    'terms.acceptanceNotice': 'Al usar JMarkets, reconoces que has leído, entendido y aceptas estar vinculado por todos los términos y condiciones descritos en este documento. Si no estás de acuerdo con ninguna parte de estos términos, por favor deja de usar nuestra plataforma.',
    'privacy.information.content': 'Recopilamos información que nos proporcionas directamente, como cuando creas una cuenta, realizas una compra o nos contactas. Esto incluye tu nombre, dirección de correo electrónico, contraseña e información de pago. También recopilamos información automáticamente cuando usas nuestra plataforma, incluyendo datos de registro, cookies e información del dispositivo.',
    'privacy.usage.content': 'Utilizamos tu información para proporcionar, mantener y mejorar nuestros servicios, procesar transacciones, enviar correos electrónicos transaccionales y promocionales, responder a tus consultas y cumplir con obligaciones legales. Utilizamos datos de análisis para entender cómo interactúas con nuestra plataforma y para optimizar la experiencia del usuario.',
    'privacy.storage.content': 'Tus datos se almacenan en servidores seguros con tecnología de cifrado. Implementamos salvaguardas físicas, electrónicas y procedimentales apropiadas para proteger tu información contra acceso, alteración, divulgación o destrucción no autorizados. Sin embargo, ningún método de transmisión a través de Internet es completamente seguro.',
    'privacy.cookies.content': 'Utilizamos cookies y tecnologías de seguimiento similares para rastrear la actividad en nuestra plataforma y retener cierta información. Puedes instruir a tu navegador para rechazar todas las cookies o para alertarte cuando se envíe una cookie. Sin embargo, algunas características de la plataforma pueden no funcionar correctamente sin cookies.',
    'privacy.third.content': 'Podemos compartir tu información con proveedores de servicios de terceros que nos ayudan a operar nuestra plataforma y conducir nuestro negocio. Estos proveedores están obligados contractualmente a usar tu información solo según sea necesario para proporcionarnos servicios.',
    'privacy.rights.content': 'Dependiendo de tu ubicación, puedes tener ciertos derechos con respecto a tus datos personales, incluido el derecho a acceder, corregir, eliminar o transferir tu información. Para ejercer cualquiera de estos derechos, contáctanos en privacy@jmarkets.com.',
    'privacy.protection.content': 'Cumplimos con las regulaciones de protección de datos aplicables, incluyendo el GDPR y leyes similares. Mantenemos salvaguardas apropiadas para proteger tus datos y solo retenemos información por el tiempo necesario para proporcionar nuestros servicios y cumplir con obligaciones legales.',
    'privacy.contact.content': 'Si tienes preguntas sobre esta política de privacidad o nuestras prácticas de privacidad, contáctanos en privacy@jmarkets.com o visita nuestra página de contacto. Estamos comprometidos a trabajar contigo para resolver cualquier preocupación sobre privacidad.',
    'privacy.lastUpdatedDate': '1 de enero de 2024',
    'privacy.notice': 'Tu Privacidad es Importante',
    'privacy.noticeDesc': 'Estamos comprometidos a proteger tu privacidad y asegurar que tengas una experiencia positiva en nuestra plataforma. Si tienes preguntas sobre cómo manejamos tus datos, no dudes en contactarnos.',
    'contact.sendMessage': 'Envíanos un mensaje',
    'contact.namePlaceholder': 'Juan Pérez',
    'contact.emailPlaceholder': 'juan@ejemplo.com',
    'contact.subjectPlaceholder': '¿Cómo podemos ayudarte?',
    'contact.messagePlaceholder': 'Tu mensaje aquí...',
    'contact.tryAgain': 'Por favor, inténtalo de nuevo.',
    'contact.otherWays': 'Otras formas de contactarnos',
    'contact.responseTime': 'Tiempo de Respuesta',
    'contact.responseTimeDesc': '¡Generalmente respondemos a todas las consultas dentro de 24 horas durante los días laborales. ¡Gracias por tu paciencia!',
    'about.ourStory': 'Nuestra Historia',
    'about.storyPara1': 'JMarkets fue fundado con una visión simple: democratizar el e-commerce y hacerlo accesible para todos. Reconocimos que muchos emprendedores talentosos y pequeños propietarios de negocios carecían de las habilidades técnicas o recursos financieros para crear y gestionar tiendas en línea profesionales.',
    'about.storyPara2': 'Lo que comenzó como un pequeño proyecto se ha convertido en una plataforma integral confiable por miles de empresas en todo el mundo. Hemos evolucionado continuamente nuestras ofertas basándonos en comentarios de nuestros usuarios, manteniendo siempre su éxito en el centro de todo lo que hacemos.',
    'about.storyPara3': 'Hoy en día, JMarkets es un testimonio del poder del emprendimiento y la comunidad. Estamos orgullosos de apoyar a empresas de todos los tamaños en lograr sus objetivos de crecimiento en línea, y nos mantenemos comprometidos con la innovación, la seguridad y el éxito del cliente.',
    'about.stats.stores': 'Tiendas Activas',
    'about.stats.storesNumber': '5,000+',
    'about.stats.countries': 'Países',
    'about.stats.countriesNumber': '50+',
    'about.stats.transactions': 'Transacciones Procesadas',
    'about.stats.transactionsNumber': '$100M+',
    'about.teamHeading': 'Dedicados a Tu Éxito',
    'about.teamDesc': 'Nuestro equipo está compuesto por profesionales apasionados con experiencia en tecnología, negocios y servicio al cliente. Estamos unidos por un objetivo común: empoderar a los emprendedores y ayudarlos a triunfar en el mercado digital. Ya sea que necesites asistencia técnica, asesoramiento empresarial o simplemente encouragement, nuestro equipo está aquí para ti.',
    'blog.latestArticles': 'Artículos Más Recientes',
    'blog.stayUpdated': 'Mantente Actualizado',
    'blog.newsletter': 'Suscríbete a nuestro boletín y recibe los últimos artículos, consejos y actualizaciones en tu bandeja de entrada.',
    'blog.subscribe': 'Suscribirse',
    'blog.privacyNote': 'Respetamos tu privacidad. Puedes desuscribirte en cualquier momento.',
    'blog.article1.title': 'Cómo Comenzar con Tu Tienda en Línea',
    'blog.article1.excerpt': 'Aprende los fundamentos de configurar tu primera tienda de e-commerce y optimizarla para el éxito.',
    'blog.article1.author': 'Sarah Johnson',
    'blog.article1.date': '15 de enero de 2024',
    'blog.article2.title': '10 Consejos para Aumentar tus Ventas en Línea',
    'blog.article2.excerpt': 'Estrategias probadas para aumentar conversiones y hacer crecer los ingresos de tu negocio.',
    'blog.article2.author': 'Michael Chen',
    'blog.article2.date': '10 de enero de 2024',
    'blog.article3.title': 'Entendiendo tu Análisis de Clientes',
    'blog.article3.excerpt': 'Cómo interpretar datos de análisis para tomar mejores decisiones comerciales.',
    'blog.article3.author': 'Emma Rodriguez',
    'blog.article3.date': '5 de enero de 2024',
    'blog.article4.title': 'Seguridad de Pasarelas de Pago: Lo Que Necesitas Saber',
    'blog.article4.excerpt': 'Una guía integral para asegurar la información de pago de tus clientes.',
    'blog.article4.author': 'James Wilson',
    'blog.article4.date': '28 de diciembre de 2023',
    'blog.article5.title': 'Mejores Prácticas en Gestión de Inventario',
    'blog.article5.excerpt': 'Optimiza tu inventario para reducir costos y mejorar la satisfacción del cliente.',
    'blog.article5.author': 'Lisa Anderson',
    'blog.article5.date': '20 de diciembre de 2023',
    'blog.article6.title': 'Estrategias de Email Marketing para E-commerce',
    'blog.article6.excerpt': 'Construye lealtad de clientes a través de campañas de correo electrónico efectivas.',
    'blog.article6.author': 'David Martinez',
    'blog.article6.date': '12 de diciembre de 2023',
    'auth.login.title': 'JMarkets',
    'auth.login.subtitle': 'Inicia sesión en tu cuenta',
    'auth.login.email': 'Email',
    'auth.login.emailPlaceholder': 'tu@email.com',
    'auth.login.password': 'Contraseña',
    'auth.login.passwordPlaceholder': 'Ingresa tu contraseña',
    'auth.login.submit': 'Iniciar sesión',
    'auth.login.submitting': 'Iniciando sesión...',
    'auth.login.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.login.noAccount': '¿No tienes cuenta?',
    'auth.login.register': 'Regístrate',
    'auth.login.backToHome': 'Volver al inicio',
    'auth.login.success': 'Inicio de sesión exitoso',
    'auth.login.successDescription': 'Bienvenido de vuelta',
    'auth.login.error': 'Error de inicio de sesión',
    'auth.register.title': 'Crear cuenta',
    'auth.register.subtitle': 'Comienza a crear tu tienda hoy',
    'auth.register.steps.personalInfo': 'Información Personal',
    'auth.register.steps.personalInfoDesc': 'Información básica',
    'auth.register.steps.security': 'Seguridad',
    'auth.register.steps.securityDesc': 'Crear contraseña',
    'auth.register.steps.verify': 'Verificar',
    'auth.register.steps.verifyDesc': 'Verificación de email',
    'auth.register.firstName': 'Nombre',
    'auth.register.firstNamePlaceholder': 'Tu nombre',
    'auth.register.lastName': 'Apellido',
    'auth.register.lastNamePlaceholder': 'Tu apellido',
    'auth.register.email': 'Email',
    'auth.register.emailPlaceholder': 'tu@email.com',
    'auth.register.gender': 'Género (opcional)',
    'auth.register.gender.placeholder': 'Selecciona tu género...',
    'auth.register.gender.male': 'Masculino',
    'auth.register.gender.female': 'Femenino',
    'auth.register.gender.other': 'Otro',
    'auth.register.gender.otherPlaceholder': 'Por favor especifica...',
    'auth.register.gender.preferNotToSay': 'Prefiero no decir',
    'auth.register.password': 'Contraseña',
    'auth.register.passwordPlaceholder': 'Crea una contraseña',
    'auth.register.confirmPassword': 'Confirmar contraseña',
    'auth.register.confirmPasswordPlaceholder': 'Confirma tu contraseña',
    'auth.register.continue': 'Continuar',
    'auth.register.back': 'Atrás',
    'auth.register.createAccount': 'Crear cuenta',
    'auth.register.submit': 'Crear cuenta',
    'auth.register.submitting': 'Creando cuenta...',
    'auth.register.hasAccount': '¿Ya tienes cuenta?',
    'auth.register.signIn': 'Inicia sesión',
    'auth.register.login': 'Inicia sesión',
    'auth.register.backToHome': 'Volver al inicio',
    'auth.register.success': 'Cuenta creada',
    'auth.register.successDescription': 'Revisa tu email para verificar tu cuenta',
    'auth.register.complete': 'Registro completo',
    'auth.register.completeDescription': 'Tu cuenta está lista para usar',
    'auth.register.completeStep1': 'Por favor completa el paso 1 primero',
    'auth.register.error': 'Error al crear cuenta',
    'auth.register.passwordMismatch': 'Las contraseñas no coinciden',
    'auth.register.passwordRequirements.minLength': 'Mínimo 8 caracteres',
    'auth.register.passwordRequirements.lowercase': 'Una letra minúscula',
    'auth.register.passwordRequirements.uppercase': 'Una letra mayúscula',
    'auth.register.passwordRequirements.number': 'Un número',
    'auth.register.passwordRequirements.special': 'Un carácter especial',
    'auth.register.passwordStrength.label': 'Fortaleza de Contraseña',
    'auth.register.passwordStrength.weak': 'Débil',
    'auth.register.passwordStrength.fair': 'Regular',
    'auth.register.passwordStrength.good': 'Buena',
    'auth.register.passwordStrength.strong': 'Fuerte',
    'auth.register.passwordStrength.excellent': 'Excelente',
    'auth.forgotPassword.title': '¿Olvidaste tu contraseña?',
    'auth.forgotPassword.subtitle': 'Ingresa tu email y te enviaremos un código de recuperación',
    'auth.forgotPassword.email': 'Email',
    'auth.forgotPassword.emailPlaceholder': 'tu@email.com',
    'auth.forgotPassword.submit': 'Enviar código',
    'auth.forgotPassword.submitting': 'Enviando...',
    'auth.forgotPassword.backToLogin': 'Volver a iniciar sesión',
    'auth.forgotPassword.success': 'Código enviado',
    'auth.forgotPassword.successDescription': 'Revisa tu email para el código de recuperación',
    'auth.forgotPassword.error': 'Error al enviar código',
    'auth.forgotPassword.checkEmail.title': 'Revisa tu email',
    'auth.forgotPassword.checkEmail.subtitle': 'Hemos enviado un código de recuperación a',
    'auth.forgotPassword.checkEmail.enterCode': 'Ingresar código',
    'auth.forgotPassword.checkEmail.differentEmail': 'Usar otro email',
    'auth.resetPassword.title': 'Restablecer contraseña',
    'auth.resetPassword.subtitle': 'Ingresa el código de tu email y tu nueva contraseña',
    'auth.resetPassword.email': 'Email',
    'auth.resetPassword.emailPlaceholder': 'tu@email.com',
    'auth.resetPassword.code': 'Código de recuperación',
    'auth.resetPassword.codePlaceholder': 'Ingresa el código de 6 dígitos',
    'auth.resetPassword.newPassword': 'Nueva contraseña',
    'auth.resetPassword.newPasswordPlaceholder': 'Ingresa tu nueva contraseña',
    'auth.resetPassword.confirmPassword': 'Confirmar contraseña',
    'auth.resetPassword.confirmPasswordPlaceholder': 'Confirma tu nueva contraseña',
    'auth.resetPassword.submit': 'Restablecer contraseña',
    'auth.resetPassword.submitting': 'Restableciendo...',
    'auth.resetPassword.requestNewCode': 'Solicitar nuevo código',
    'auth.resetPassword.backToHome': 'Volver al inicio',
    'auth.resetPassword.success': 'Contraseña restablecida',
    'auth.resetPassword.successDescription': 'Ya puedes iniciar sesión con tu nueva contraseña',
    'auth.resetPassword.error': 'Error al restablecer contraseña',
    'auth.resetPassword.invalidCode': 'Código inválido',
    'auth.resetPassword.invalidCodeDescription': 'El código ingresado es incorrecto',
    'auth.resetPassword.expiredCode': 'Código expirado',
    'auth.resetPassword.expiredCodeDescription': 'Por favor solicita un nuevo código',
    'auth.verifyEmail.title': 'Verifica tu email',
    'auth.verifyEmail.subtitle': 'Ingresa el código de verificación enviado a',
    'auth.verifyEmail.code': 'Código de verificación',
    'auth.verifyEmail.submit': 'Verificar',
    'auth.verifyEmail.submitting': 'Verificando...',
    'auth.verifyEmail.resendCode': 'Reenviar código',
    'auth.verifyEmail.resending': 'Reenviando...',
    'auth.verifyEmail.didntReceive': '¿No recibiste el código?',
    'auth.verifyEmail.success': 'Email verificado',
    'auth.verifyEmail.successDescription': 'Tu cuenta ha sido verificada exitosamente',
    'auth.verifyEmail.error': 'Error de verificación',
    'auth.verifyEmail.resendSuccess': 'Código reenviado',
    'auth.verifyEmail.resendSuccessDescription': 'Revisa tu email para el nuevo código',
    'organizations.create.title': 'Crea tu organización',
    'organizations.create.subtitle': 'Configura tu tienda en minutos',
    'organizations.create.name': 'Nombre de la tienda',
    'organizations.create.namePlaceholder': 'Mi Tienda',
    'organizations.create.nameDescription': 'El nombre público de tu tienda',
    'organizations.create.slug': 'URL de la tienda',
    'organizations.create.slugPlaceholder': 'mi-tienda',
    'organizations.create.slugDescription': 'La URL única de tu tienda',
    'organizations.create.subdomain': 'Subdominio',
    'organizations.create.subdomainDescription': 'Tu tienda estará disponible en',
    'organizations.create.submit': 'Crear tienda',
    'organizations.create.submitting': 'Creando tienda...',
    'organizations.create.success': 'Tienda creada',
    'organizations.create.successDescription': 'Tu tienda está lista',
    'organizations.create.error': 'Error al crear tienda',
    'organizations.create.slugTaken': 'Esta URL ya está en uso',
    'organizations.create.subdomainTaken': 'Este subdominio ya está en uso',
    'organizations.create.checking': 'Verificando disponibilidad...',
    'organizations.select.title': 'Selecciona tu organización',
    'organizations.select.subtitle': 'Elige la tienda que deseas administrar',
    'organizations.select.createNew': 'Crear nueva tienda',
    'organizations.select.noOrganizations': 'No tienes organizaciones',
    'organizations.select.noOrganizationsDescription': 'Crea tu primera tienda para comenzar',
    'organizations.select.loading': 'Cargando organizaciones...',
    'organizations.select.visitStore': 'Visitar tienda',
    'organizations.select.manage': 'Administrar',
    'theme.light': 'Claro',
    'theme.dark': 'Oscuro',
    'theme.system': 'Sistema',
    'language.es': 'Español',
    'language.en': 'English',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    if (saved) return saved;
    const browserLang = navigator.language.toLowerCase();
    return browserLang.startsWith('es') ? 'es' : 'en';
  });

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return (translations[language] as Record<string, string>)[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
