import { createContext, useContext, useState } from "react";

type Language = "en" | "es";

interface LanguageContextValue {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string | number>) => string;
}

const translations: Record<Language, Record<string, string>> = {
  es: {
    // common
    "common.loading": "Cargando…",
    "common.save": "Guardar",
    "common.saving": "Guardando…",
    "common.cancel": "Cancelar",
    "common.confirm": "Confirmar",
    "common.continue": "Continuar",
    "common.back": "Atrás",
    "common.close": "Cerrar",
    "common.error": "Error",
    "common.refresh": "Actualizar",
    "common.search": "Buscar",
    "common.delete": "Eliminar",
    "common.activate": "Activar",
    "common.deactivate": "Desactivar",
    "common.noResults": "Sin resultados",
    "common.active": "Activo",
    "common.inactive": "Inactivo",
    "common.print": "Imprimir",
    "common.edit": "Editar",
    "common.view": "Ver",

    // auth
    "auth.email": "CORREO",
    "auth.emailPlaceholder": "usuario@ejemplo.com",
    "auth.password": "CONTRASEÑA",
    "auth.login": "INGRESAR",
    "auth.loggingIn": "Ingresando…",
    "auth.loginError": "Error al iniciar sesión",
    "auth.systemTitle": "Sistema de Ventas",

    // orgs
    "orgs.loading": "Cargando organizaciones…",
    "orgs.noOrgs": "No tenés organizaciones disponibles.",
    "orgs.contactAdmin": "Contactá al administrador para obtener acceso.",
    "orgs.selectTitle": "SELECCIONÁ TU ORGANIZACIÓN",

    // app
    "app.noPermissions": "No tenés permisos para acceder a esta página.",
    "app.yourRole": "Tu rol:",

    // pos
    "pos.noAssignment": "No hay asignación activa.",
    "pos.contactManager": "Contactá al gerente para iniciar turno.",
    "pos.searchProduct": "Buscar producto…",
    "pos.allCategories": "Todo",
    "pos.closeShift": "Cerrar turno",
    "pos.viewOrder": "Ver orden",
    "pos.currentOrder": "Orden actual",
    "pos.charge": "Cobrar",
    "pos.saleDone": "Venta completada",
    "pos.paymentMethod": "Método de pago",
    "pos.cash": "Efectivo",
    "pos.card": "Tarjeta",
    "pos.sinpe": "SINPE",
    "pos.cashReceived": "Efectivo recibido",
    "pos.received": "Recibido",
    "pos.total": "Total",
    "pos.change": "Vuelto",
    "pos.swipeCard": "Pasar tarjeta en el POS",
    "pos.amountToCharge": "Monto a cobrar:",
    "pos.sinpeMobile": "SINPE móvil",
    "pos.sinpeLastDigits": "Últimos 4 dígitos del SMS",
    "pos.confirmCharge": "Confirmar cobro {amount}",
    "pos.backToOrder": "Volver a la orden",
    "pos.saleRegistered": "¡Venta registrada!",
    "pos.deliverChange": "Entregar vuelto",
    "pos.newSale": "Nueva venta",
    "pos.cashier": "Cajero",
    "pos.orderNum": "Orden #{num}",
    "pos.emptyCart": "Seleccioná productos",
    "pos.items": "{n} ítem{s}",

    // payment
    "payment.title": "Cobro",
    "payment.totalLabel": "TOTAL A COBRAR",
    "payment.receivedLabel": "MONTO RECIBIDO",
    "payment.return": "Devolver",
    "payment.remaining": "Faltan {amount}",
    "payment.sinpeTitle": "SINPE MÓVIL — NÚMERO DESTINO",
    "payment.sinpeInstruction": "Pedile al cliente que transfiera {amount}",
    "payment.cardInstruction": "Pasá la tarjeta por el datafono",
    "payment.amountLabel": "Monto:",
    "payment.registering": "Registrando…",
    "payment.confirm": "Confirmar {method}",

    // success
    "success.title": "Venta registrada",
    "success.returnClient": "DEVOLVER AL CLIENTE",
    "success.syncPending": "sync pendiente",
    "success.newSale": "Nueva venta",

    // inv (InventoryOpening)
    "inv.back": "Volver",
    "inv.shiftOpening": "Apertura de turno",
    "inv.initialCount": "Conteo inicial",
    "inv.progress": "Progreso",
    "inv.products": "productos",
    "inv.progressLabel": "{filled}/{total} productos",
    "inv.initialCash": "Efectivo inicial",
    "inv.initialFund": "Fondo entregado por el gerente",
    "inv.countUnits": "Productos · contar unidades",
    "inv.sku": "SKU {sku} · {price}",
    "inv.subtract": "Restar",
    "inv.add": "Sumar",
    "inv.inventoryValue": "Valor inventario",
    "inv.openShift": "Abrir turno",
    "inv.confirmTitle": "Confirmar apertura",
    "inv.confirmMessage": "Al confirmar, el turno queda abierto y no podés cambiar el conteo inicial.",
    "inv.productsLabel": "Productos",
    "inv.cashLabel": "Efectivo inicial",
    "inv.stockValue": "Valor en stock",
    "inv.items": "{n} items",
    "inv.saveError": "Error al guardar. Intentá de nuevo.",
    "inv.saving": "Guardando…",
    "inv.cancel": "Cancelar",
    "inv.confirm": "Confirmar",

    // closing
    "closing.title": "Cierre de turno",
    "closing.step": "Paso {n} de {total}",
    "closing.closing": "Cerrando",
    "closing.stepInventory": "Inventario",
    "closing.stepCash": "Efectivo",
    "closing.stepSummary": "Resumen",
    "closing.countRemaining": "Contá lo que te queda",
    "closing.systemCompares": "El sistema compara con lo que debería quedar según las ventas.",
    "closing.expectedRemaining": "Restante esperado:",
    "closing.totalExpected": "Total esperado en caja",
    "closing.initialFundSales": "Fondo inicial + ventas en efectivo",
    "closing.cashBreakdown": "Desglose de efectivo",
    "closing.bill20k": "Billete ₡20.000",
    "closing.bill10k": "Billete ₡10.000",
    "closing.bill5k": "Billete ₡5.000",
    "closing.bill2k": "Billete ₡2.000",
    "closing.bill1k": "Billete ₡1.000",
    "closing.coin500": "Moneda ₡500",
    "closing.coin100": "Moneda ₡100",
    "closing.counted": "Contado",
    "closing.expected": "Esperado",
    "closing.surplus": "Sobrante",
    "closing.shortage": "Faltante",
    "closing.difference": "Diferencia",
    "closing.shiftStation": "Turno · Puesto",
    "closing.finalSummary": "Resumen final",
    "closing.sales": "Ventas",
    "closing.shiftOrders": "Órdenes del turno",
    "closing.cashLabel": "Efectivo",
    "closing.productShortages": "Faltantes de producto",
    "closing.allBalanced": "Todo cuadra perfectamente",
    "closing.notes": "Observaciones (opcional)",
    "closing.notesPlaceholder": "Notas para el gerente…",
    "closing.back": "Atrás",
    "closing.continue": "Continuar",
    "closing.sending": "Enviando…",
    "closing.closeShift": "Cerrar turno",
    "closing.closeSent": "Cierre enviado",
    "closing.managerWillReview": "El gerente revisará el informe.",
    "closing.cashier": "Cajero",
    "closing.closingLabel": "Cerrando",

    // dash
    "dash.morningGreeting": "Buenos días",
    "dash.afternoonGreeting": "Buenas tardes",
    "dash.eveningGreeting": "Buenas noches",
    "dash.activeStations": "{n} puestos activos en tiempo real.",
    "dash.refreshing": "Actualizando…",
    "dash.refresh": "Actualizar",
    "dash.sessionSales": "Ventas del partido",
    "dash.orders": "Órdenes",
    "dash.avgTicket": "Ticket promedio",
    "dash.activeStationsLabel": "Puestos activos",
    "dash.allSynced": "Todos sincronizados",
    "dash.hourlyChart": "Ventas por hora",
    "dash.currentSession": "Sesión actual",
    "dash.liveStations": "Puestos en vivo",
    "dash.stationStatus": "Estado de cada caja",
    "dash.active": "{n} activos",
    "dash.loading": "Cargando…",
    "dash.noActiveStations": "No hay puestos activos",
    "dash.stationOrders": "{n} órdenes",
    "dash.topProducts": "Top productos",
    "dash.bestSellers": "Más vendidos hoy",
    "dash.noSalesData": "Sin datos de ventas aún",
    "dash.units": "{n} unidades",
    "dash.salesFeed": "Feed de ventas",
    "dash.realTime": "En tiempo real",
    "dash.live": "Live",
    "dash.ordersRegistered": "{n} órdenes registradas",
    "dash.noRecentSales": "No hay ventas recientes",
    "dash.noOrgSelected": "No hay organización seleccionada",
    "dash.selectOrg": "Seleccionar organización",
    "dash.managerPanel": "Panel gerente",
    "dash.goToPOS": "Ir al POS",

    // products
    "products.title": "Catálogo",
    "products.subtitle": "Productos compartidos por todas las sucursales.",
    "products.newProduct": "Nuevo producto",
    "products.searchPlaceholder": "Buscar por nombre…",
    "products.cards": "Tarjetas",
    "products.table": "Tabla",
    "products.selected": "{n} seleccionados",
    "products.loading": "Cargando…",
    "products.noProducts": "No hay productos",
    "products.noResults": "No se encontraron productos con esos filtros.",
    "products.inactive": "Inactivo",
    "products.stock": "Stock {n}",
    "products.product": "Producto",
    "products.category": "Categoría",
    "products.price": "Precio",
    "products.status": "Estado",
    "products.showing": "Mostrando {n} de {total}",
    "products.editProduct": "Editar producto",
    "products.image": "Imagen",
    "products.name": "Nombre",
    "products.namePlaceholder": "Ej. Pollo entero",
    "products.description": "Descripción",
    "products.descriptionPlaceholder": "Descripción opcional",
    "products.priceLabel": "Precio (₡)",
    "products.categoryLabel": "Categoría",
    "products.noCategory": "Sin categoría",
    "products.sku": "SKU",
    "products.internalCode": "Código interno",
    "products.trackInventory": "Rastrear inventario",
    "products.trackInventoryDesc": "Controlar stock mínimo",
    "products.minStockLabel": "Stock mínimo",
    "products.minStockPlaceholder": "Ej. 5",
    "products.activeLabel": "Activo",
    "products.inactiveLabel": "Inactivo",
    // Product form — sections common
    "products.loadingInfo": "Cargando información…",
    "products.generalInfo": "Información General",
    "products.unitOfMeasure": "Unidad de medida",
    "products.selectUnit": "Seleccionar unidad…",
    "products.otherUnit": "Otros…",
    "products.specifyUnit": "Especificar unidad",
    "products.fiscalInfo": "Información fiscal",
    "products.fiscalInfoDesc": "Habilitar CABYS, IVA y datos fiscales",
    "products.packageInfo": "Información de empaque",
    "products.packageInfoDesc": "Unidades por caja y detalles de empaque",
    "products.lowStockHint": "Se enviará una alerta cuando el stock llegue a este nivel.",
    "products.inventoryTitle": "Gestión de inventario",
    // Packaging
    "products.unitsPerBox": "Unidades por caja",
    "products.unitsPerBoxPlaceholder": "Ej: 12",
    // Codes
    "products.productCodes": "Códigos del producto",
    "products.codeValue": "Valor del código",
    "products.specifyType": "Especificar tipo",
    "products.codeTypePlaceholder": "Describe el tipo de código",
    "products.addCodeType": "Agregar tipo de código…",
    // Fiscal
    "products.fiscalInformation": "Información fiscal",
    "products.productType": "Tipo de producto",
    "products.searchCabys": "Buscar CABYS",
    "products.selectProductTypeFirst": "Selecciona un tipo de producto primero",
    "products.searchByName": "Buscar por nombre del producto…",
    "products.noResultsFor": "Sin resultados para \"{query}\"",
    "products.cabysHelp": "Código CABYS de Hacienda (13 dígitos). Requerido para facturación electrónica.",
    "products.suggestedIva": "IVA sugerido: {pct}%",
    "products.changeProductType": "Cambiar tipo de producto",
    "products.changeProductTypeWarning": "Cambiar el tipo de producto eliminará el CABYS seleccionado y el IVA asociado. ¿Deseas continuar?",
    // Discounts
    "products.discounts": "Descuentos",
    "products.noDiscountsHint": "Sin descuentos. Selecciona un tipo abajo para agregar.",
    "products.discountReason": "Razón",
    "products.discountReasonPlaceholder": "Describa el motivo del descuento",
    "products.discountTotal": "Total:",
    "products.discountExceeds": "¡No puede exceder 100%!",
    "products.addDiscount": "Agregar descuento…",
    // Other taxes
    "products.otherTaxes": "Otros impuestos",
    "products.alcoholPercentage": "Porcentaje alcohólico",
    "products.alcoholPercentageExample": "Ej: 5.5",
    "products.amountPerUnit": "₡{amount} / unidad — {desc}",
    "products.noAmountForPercentage": "No hay monto para ese porcentaje",
    "products.taxAmountLabel": "Monto de impuesto",
    "products.selectAmount": "Seleccionar monto…",
    "products.quantityUdm": "Cantidad UdM",
    "products.percentage": "Porcentaje",
    "products.volumePerUnit": "Volumen por unidad",
    "products.addTax": "Agregar impuesto…",
    // IVA
    "products.iva": "IVA",
    "products.taxRate": "Tasa…",
    "products.ivarbuFactor": "Factor IVARBU",
    "products.selectFactor": "Seleccionar factor…",
    "products.addIva": "Agregar IVA…",
    "products.factoryTaxCharge": "Cargo de fábrica (impuesto asumido)",
    "products.noFactoryCharge": "Sin cargo de fábrica",
    "products.factoryTaxAssumed": "El impuesto de fábrica se asume en el precio — afecta el cálculo del total.",
    "products.factoryTaxNotAssumed": "Cargo de fábrica sin impuesto asumido.",
    // Commercial value
    "products.commercialPrice": "Precio comercial",
    "products.basePriceNoTax": "Precio base (sin impuestos)",
    "products.estimatedSalePrice": "Precio de venta estimado",
    "products.basePriceLine": "Precio base",
    "products.netPrice": "Precio neto",
    "products.baseForIva": "Base para IVA",
    "products.factoryAssumedTax": "Impuesto asumido fábrica",
    "products.totalIva": "Total IVA",
    "products.totalOtherTaxes": "Total otros impuestos",

    // shell
    "shell.navigation": "Navegación",
    "shell.panel": "Panel",
    "shell.sessions": "Sesiones",
    "shell.stations": "Puestos",
    "shell.products": "Productos",
    "shell.clients": "Clientes",
    "shell.reports": "Reportes",
    "shell.logout": "Salir",
    "shell.liveLabel": "En vivo",
    "shell.activeSession": "Sesión activa",
    "shell.sync": "Sincronizar",

    // cart
    "cart.item": "ítem",
    "cart.items": "ítems",
    "cart.selectProducts": "Seleccioná productos",

    // report
    "report.finalReport": "Reporte final",
    "report.loading": "Cargando reporte…",
    "report.downloadPdf": "Descargar PDF",
    "report.grossIncome": "Ingreso bruto",
    "report.orders": "Órdenes",
    "report.avgTicket": "Ticket promedio",
    "report.cashDiff": "Diferencia caja",
    "report.balanced": "Cuadrado",
    "report.allStandsBalanced": "Todos los puestos cuadran",
    "report.standsWithDiff": "Puestos con diferencia",
    "report.paymentMethods": "Métodos de pago",
    "report.distribution": "Distribución del total",
    "report.cash": "Efectivo",
    "report.card": "Tarjeta",
    "report.sinpeMobile": "SINPE Móvil",
    "report.standPerformance": "Rendimiento por puesto",
    "report.productsTable": "Productos vendidos",
    "report.units": "Unidades",
    "report.revenue": "Ingreso",
    "report.total": "Total",
    "report.noProductData": "Sin datos de productos.",
    "report.noStandData": "Sin datos de puestos.",
    "report.print": "Imprimir",
    "report.csv": "CSV",

    // assignments
    "assignments.title": "Asignaciones activas",
    "assignments.count": "{n} asignación(es) en curso",
    "assignments.newAssignment": "Nueva asignación",
    "assignments.loading": "Cargando asignaciones…",
    "assignments.noActive": "Sin asignaciones activas",
    "assignments.station": "Puesto: {id}",
    "assignments.start": "Inicio: {time}",
    "assignments.finish": "Finalizar",
    "assignments.session": "Sesión",
    "assignments.seller": "Vendedor",
    "assignments.role": "Rol",
    "assignments.cashier": "Cajero",
    "assignments.supervisor": "Supervisor",
    "assignments.assigning": "Asignando…",
    "assignments.create": "Crear asignación",

    // puestos
    "puestos.title": "Puestos",
    "puestos.subtitle": "{active} activos · {total} en total",
    "puestos.newStation": "Nuevo puesto",
    "puestos.all": "Todos",
    "puestos.stand": "Stand",
    "puestos.restaurant": "Restaurante",
    "puestos.onlyActive": "Solo activos",
    "puestos.addTerminal": "Agregar terminal",
    "puestos.terminals": "Terminales",

    // mobile dashboard
    "mobile.panel": "Panel gerente",
    "mobile.orders": "Órdenes",
    "mobile.ticket": "Ticket",
    "mobile.stations": "Puestos",
    "mobile.cashiers": "Cajeros",
    "mobile.sessionSales": "Ventas del partido",
    "mobile.live": "En vivo",
    "mobile.summary": "Resumen",
    "mobile.stationsTab": "Puestos",
    "mobile.topTab": "Top",
    "mobile.lastSales": "Últimas ventas",
    "mobile.liveFeed": "Feed en tiempo real",
    "mobile.noSales": "Sin ventas aún.",
    "mobile.noCashier": "Sin cajero",
    "mobile.stationOrders": "{n} órdenes",
    "mobile.noProductData": "Sin datos de productos.",
    "mobile.noActiveStations": "Sin puestos activos.",
    "mobile.timeAgo": "hace {time}",

    // session config
    "session.title": "Configurar sesión",
    "session.subtitle": "Creá un nuevo partido o día operativo y asigná cajeros a cada puesto.",
    "session.activating": "Activando…",
    "session.activate": "Activar sesión",
    "session.requiredSteps": "Para activar completá",
    "session.selectBranches": "Seleccioná al menos un puesto",
    "session.assignMembers": "Asigná cajero a cada puesto",
    "session.selectDate": "Seleccioná fecha y hora",
    "session.selectProducts": "Seleccioná al menos un producto",
    "session.tabMatch": "Datos del partido",
    "session.tabStations": "Puestos y asignaciones",
    "session.tabInventory": "Inventario inicial",
    "session.sessionInfo": "Información de la sesión",
    "session.sessionInfoDesc": "Los cajeros verán este contexto al abrir turno.",
    "session.sessionType": "Tipo de sesión",
    "session.match": "Partido",
    "session.matchDesc": "Ventas en estadio",
    "session.regular": "Día regular",
    "session.regularDesc": "Operación restaurante",
    "session.rivalTeam": "Equipo rival",
    "session.matchTime": "Hora del partido",
    "session.date": "Fecha",
    "session.mainBranch": "Sucursal principal",
    "session.noBranch": "Sin sucursal",
    "session.preview": "Vista previa",
    "session.previewDesc": "Así la verán los cajeros",
    "session.vsRival": "vs Rival",
    "session.regularOp": "Operación regular",
    "session.noDate": "Sin fecha",
    "session.stations": "Puestos",
    "session.assigned": "Asignados",
    "session.selectStations": "Seleccionar puestos",
    "session.activeForSession": "{n} puestos activos para esta sesión",
    "session.noBranches": "No hay sucursales disponibles.",
    "session.assignments": "Asignaciones",
    "session.assignedCount": "{n}/{total} puestos con cajero asignado",
    "session.cashier": "Cajero",
    "session.unassigned": "Sin asignar",
    "session.role": "Rol",
    "session.select": "Seleccionar…",
    "session.inventoryTitle": "Inventario inicial por puesto",
    "session.inventoryDesc": "Cantidad de cada producto a entregar al abrir turno",
    "session.selectFirst": "(Selecciona puestos primero)",
    "session.total": "Total",
    "session.noActiveProducts": "No hay productos activos.",
    "session.addMember": "Agregar miembro",
    "session.noMembers": "Sin miembros asignados",
    "session.member": "Miembro",
    "session.terminal": "Terminal",
    "session.noTerminal": "Sin terminal",
    "session.manageActiveSessions": "Gestionar sesiones activas y cerradas",
    "session.newSession": "Nueva sesión",
    "session.allSessions": "Todas",
    "session.activeSessions": "Activas",
    "session.closedSessions": "Cerradas",
    "session.noSessions": "No hay sesiones aún",
    "session.createFirstSession": "Crea tu primera sesión para iniciar operaciones",
    "session.active": "Activa",
    "session.startTime": "Hora de inicio",
    "session.endTime": "Hora de fin",
    "session.endSession": "Finalizar sesión",
    "session.confirmEnd": "¿Estás seguro de que quieres finalizar esta sesión?",
    "session.confirmDelete": "¿Estás seguro de que quieres eliminar esta sesión?",

    // analytics
    "analytics.title": "REPORTERÍA",
    "analytics.today": "Hoy",
    "analytics.week": "Semana",
    "analytics.month": "Mes",
    "analytics.season": "Temporada",
    "analytics.revenue": "INGRESOS",
    "analytics.sales": "VENTAS",
    "analytics.topProduct": "TOP PRODUCTO",
    "analytics.topContext": "TOP CONTEXTO",
    "analytics.loading": "Cargando...",
    "analytics.tabProducts": "🏆 Productos",
    "analytics.tabSessions": "📅 Sesiones",
    "analytics.tabVendors": "👤 Vendedores",
    "analytics.tabContext": "📍 Contexto",
    "analytics.colProduct": "PRODUCTO",
    "analytics.colUnits": "UNIDADES",
    "analytics.colRevenue": "INGRESOS",
    "analytics.colVolume": "VOLUMEN",
    "analytics.colSession": "SESIÓN",
    "analytics.colType": "TIPO",
    "analytics.colDate": "FECHA",
    "analytics.colSales": "VENTAS",
    "analytics.colStatus": "ESTADO",
    "analytics.colVendor": "VENDEDOR",
    "analytics.colTransactions": "TRANSACCIONES",
    "analytics.colAvgTicket": "TICKET PROM.",
    "analytics.colFavPayment": "PAGO FAV.",
    "analytics.statusClosed": "Cerrado",
    "analytics.statusActive": "Activo",
    "analytics.salesCount": "{n} ventas",
  },

  en: {
    // common
    "common.loading": "Loading…",
    "common.save": "Save",
    "common.saving": "Saving…",
    "common.cancel": "Cancel",
    "common.confirm": "Confirm",
    "common.continue": "Continue",
    "common.back": "Back",
    "common.close": "Close",
    "common.error": "Error",
    "common.refresh": "Refresh",
    "common.search": "Search",
    "common.delete": "Delete",
    "common.activate": "Activate",
    "common.deactivate": "Deactivate",
    "common.noResults": "No results",
    "common.active": "Active",
    "common.inactive": "Inactive",
    "common.print": "Print",
    "common.edit": "Edit",
    "common.view": "View",

    // auth
    "auth.email": "EMAIL",
    "auth.emailPlaceholder": "user@example.com",
    "auth.password": "PASSWORD",
    "auth.login": "SIGN IN",
    "auth.loggingIn": "Signing in…",
    "auth.loginError": "Sign-in error",
    "auth.systemTitle": "Sales System",

    // orgs
    "orgs.loading": "Loading organizations…",
    "orgs.noOrgs": "You have no organizations available.",
    "orgs.contactAdmin": "Contact an administrator to get access.",
    "orgs.selectTitle": "SELECT YOUR ORGANIZATION",

    // app
    "app.noPermissions": "You do not have permission to access this page.",
    "app.yourRole": "Your role:",

    // pos
    "pos.noAssignment": "No active assignment.",
    "pos.contactManager": "Contact your manager to start a shift.",
    "pos.searchProduct": "Search product…",
    "pos.allCategories": "All",
    "pos.closeShift": "Close shift",
    "pos.viewOrder": "View order",
    "pos.currentOrder": "Current order",
    "pos.charge": "Charge",
    "pos.saleDone": "Sale completed",
    "pos.paymentMethod": "Payment method",
    "pos.cash": "Cash",
    "pos.card": "Card",
    "pos.sinpe": "SINPE",
    "pos.cashReceived": "Cash received",
    "pos.received": "Received",
    "pos.total": "Total",
    "pos.change": "Change",
    "pos.swipeCard": "Swipe card at the terminal",
    "pos.amountToCharge": "Amount to charge:",
    "pos.sinpeMobile": "SINPE Mobile",
    "pos.sinpeLastDigits": "Last 4 digits of the SMS",
    "pos.confirmCharge": "Confirm charge {amount}",
    "pos.backToOrder": "Back to order",
    "pos.saleRegistered": "Sale registered!",
    "pos.deliverChange": "Deliver change",
    "pos.newSale": "New sale",
    "pos.cashier": "Cashier",
    "pos.orderNum": "Order #{num}",
    "pos.emptyCart": "Select products",
    "pos.items": "{n} item{s}",

    // payment
    "payment.title": "Charge",
    "payment.totalLabel": "TOTAL TO CHARGE",
    "payment.receivedLabel": "AMOUNT RECEIVED",
    "payment.return": "Return",
    "payment.remaining": "Remaining {amount}",
    "payment.sinpeTitle": "SINPE MOBILE — DESTINATION NUMBER",
    "payment.sinpeInstruction": "Ask the customer to transfer {amount}",
    "payment.cardInstruction": "Swipe the card at the terminal",
    "payment.amountLabel": "Amount:",
    "payment.registering": "Registering…",
    "payment.confirm": "Confirm {method}",

    // success
    "success.title": "Sale registered",
    "success.returnClient": "RETURN TO CUSTOMER",
    "success.syncPending": "sync pending",
    "success.newSale": "New sale",

    // inv
    "inv.back": "Back",
    "inv.shiftOpening": "Shift opening",
    "inv.initialCount": "Initial count",
    "inv.progress": "Progress",
    "inv.products": "products",
    "inv.progressLabel": "{filled}/{total} products",
    "inv.initialCash": "Initial cash",
    "inv.initialFund": "Fund delivered by the manager",
    "inv.countUnits": "Products · count units",
    "inv.sku": "SKU {sku} · {price}",
    "inv.subtract": "Subtract",
    "inv.add": "Add",
    "inv.inventoryValue": "Inventory value",
    "inv.openShift": "Open shift",
    "inv.confirmTitle": "Confirm opening",
    "inv.confirmMessage": "Once confirmed, the shift is open and the initial count cannot be changed.",
    "inv.productsLabel": "Products",
    "inv.cashLabel": "Initial cash",
    "inv.stockValue": "Stock value",
    "inv.items": "{n} items",
    "inv.saveError": "Error saving. Please try again.",
    "inv.saving": "Saving…",
    "inv.cancel": "Cancel",
    "inv.confirm": "Confirm",

    // closing
    "closing.title": "Close shift",
    "closing.step": "Step {n} of {total}",
    "closing.closing": "Closing",
    "closing.stepInventory": "Inventory",
    "closing.stepCash": "Cash",
    "closing.stepSummary": "Summary",
    "closing.countRemaining": "Count what you have left",
    "closing.systemCompares": "The system compares with what should remain based on sales.",
    "closing.expectedRemaining": "Expected remaining:",
    "closing.totalExpected": "Total expected in register",
    "closing.initialFundSales": "Initial fund + cash sales",
    "closing.cashBreakdown": "Cash breakdown",
    "closing.bill20k": "₡20,000 bill",
    "closing.bill10k": "₡10,000 bill",
    "closing.bill5k": "₡5,000 bill",
    "closing.bill2k": "₡2,000 bill",
    "closing.bill1k": "₡1,000 bill",
    "closing.coin500": "₡500 coin",
    "closing.coin100": "₡100 coin",
    "closing.counted": "Counted",
    "closing.expected": "Expected",
    "closing.surplus": "Surplus",
    "closing.shortage": "Shortage",
    "closing.difference": "Difference",
    "closing.shiftStation": "Shift · Station",
    "closing.finalSummary": "Final summary",
    "closing.sales": "Sales",
    "closing.shiftOrders": "Shift orders",
    "closing.cashLabel": "Cash",
    "closing.productShortages": "Product shortages",
    "closing.allBalanced": "Everything balanced perfectly",
    "closing.notes": "Notes (optional)",
    "closing.notesPlaceholder": "Notes for the manager…",
    "closing.back": "Back",
    "closing.continue": "Continue",
    "closing.sending": "Sending…",
    "closing.closeShift": "Close shift",
    "closing.closeSent": "Close sent",
    "closing.managerWillReview": "The manager will review the report.",
    "closing.cashier": "Cashier",
    "closing.closingLabel": "Closing",

    // dash
    "dash.morningGreeting": "Good morning",
    "dash.afternoonGreeting": "Good afternoon",
    "dash.eveningGreeting": "Good evening",
    "dash.activeStations": "{n} active stations in real time.",
    "dash.refreshing": "Refreshing…",
    "dash.refresh": "Refresh",
    "dash.sessionSales": "Session sales",
    "dash.orders": "Orders",
    "dash.avgTicket": "Avg ticket",
    "dash.activeStationsLabel": "Active stations",
    "dash.allSynced": "All synced",
    "dash.hourlyChart": "Hourly sales",
    "dash.currentSession": "Current session",
    "dash.liveStations": "Live stations",
    "dash.stationStatus": "Status of each register",
    "dash.active": "{n} active",
    "dash.loading": "Loading…",
    "dash.noActiveStations": "No active stations",
    "dash.stationOrders": "{n} orders",
    "dash.topProducts": "Top products",
    "dash.bestSellers": "Best sellers today",
    "dash.noSalesData": "No sales data yet",
    "dash.units": "{n} units",
    "dash.salesFeed": "Sales feed",
    "dash.realTime": "Real time",
    "dash.live": "Live",
    "dash.ordersRegistered": "{n} orders registered",
    "dash.noRecentSales": "No recent sales",
    "dash.noOrgSelected": "No organization selected",
    "dash.selectOrg": "Select organization",
    "dash.managerPanel": "Manager panel",
    "dash.goToPOS": "Go to POS",

    // products
    "products.title": "Catalog",
    "products.subtitle": "Products shared across all branches.",
    "products.newProduct": "New product",
    "products.searchPlaceholder": "Search by name…",
    "products.cards": "Cards",
    "products.table": "Table",
    "products.selected": "{n} selected",
    "products.loading": "Loading…",
    "products.noProducts": "No products",
    "products.noResults": "No products found with those filters.",
    "products.inactive": "Inactive",
    "products.stock": "Stock {n}",
    "products.product": "Product",
    "products.category": "Category",
    "products.price": "Price",
    "products.status": "Status",
    "products.showing": "Showing {n} of {total}",
    "products.editProduct": "Edit product",
    "products.image": "Image",
    "products.name": "Name",
    "products.namePlaceholder": "e.g. Whole chicken",
    "products.description": "Description",
    "products.descriptionPlaceholder": "Optional description",
    "products.priceLabel": "Price (₡)",
    "products.categoryLabel": "Category",
    "products.noCategory": "No category",
    "products.sku": "SKU",
    "products.internalCode": "Internal code",
    "products.trackInventory": "Track inventory",
    "products.trackInventoryDesc": "Control minimum stock",
    "products.minStockLabel": "Minimum stock",
    "products.minStockPlaceholder": "e.g. 5",
    "products.activeLabel": "Active",
    "products.inactiveLabel": "Inactive",
    // Product form — sections common
    "products.loadingInfo": "Loading information…",
    "products.generalInfo": "General Information",
    "products.unitOfMeasure": "Unit of measure",
    "products.selectUnit": "Select unit…",
    "products.otherUnit": "Other…",
    "products.specifyUnit": "Specify unit",
    "products.fiscalInfo": "Fiscal information",
    "products.fiscalInfoDesc": "Enable CABYS, VAT and fiscal data",
    "products.packageInfo": "Packaging information",
    "products.packageInfoDesc": "Units per box and packaging details",
    "products.lowStockHint": "An alert will be sent when stock reaches this level.",
    "products.inventoryTitle": "Inventory management",
    // Packaging
    "products.unitsPerBox": "Units per box",
    "products.unitsPerBoxPlaceholder": "e.g. 12",
    // Codes
    "products.productCodes": "Product codes",
    "products.codeValue": "Code value",
    "products.specifyType": "Specify type",
    "products.codeTypePlaceholder": "Describe the code type",
    "products.addCodeType": "Add code type…",
    // Fiscal
    "products.fiscalInformation": "Fiscal information",
    "products.productType": "Product type",
    "products.searchCabys": "Search CABYS",
    "products.selectProductTypeFirst": "Select a product type first",
    "products.searchByName": "Search by product name…",
    "products.noResultsFor": "No results for \"{query}\"",
    "products.cabysHelp": "Hacienda CABYS code (13 digits). Required for electronic invoicing.",
    "products.suggestedIva": "Suggested VAT: {pct}%",
    "products.changeProductType": "Change product type",
    "products.changeProductTypeWarning": "Changing the product type will remove the selected CABYS and the linked VAT. Continue?",
    // Discounts
    "products.discounts": "Discounts",
    "products.noDiscountsHint": "No discounts. Pick a type below to add one.",
    "products.discountReason": "Reason",
    "products.discountReasonPlaceholder": "Describe the discount reason",
    "products.discountTotal": "Total:",
    "products.discountExceeds": "Cannot exceed 100%!",
    "products.addDiscount": "Add discount…",
    // Other taxes
    "products.otherTaxes": "Other taxes",
    "products.alcoholPercentage": "Alcohol percentage",
    "products.alcoholPercentageExample": "e.g. 5.5",
    "products.amountPerUnit": "₡{amount} / unit — {desc}",
    "products.noAmountForPercentage": "No amount for that percentage",
    "products.taxAmountLabel": "Tax amount",
    "products.selectAmount": "Select amount…",
    "products.quantityUdm": "Unit quantity",
    "products.percentage": "Percentage",
    "products.volumePerUnit": "Volume per unit",
    "products.addTax": "Add tax…",
    // VAT
    "products.iva": "VAT",
    "products.taxRate": "Rate…",
    "products.ivarbuFactor": "IVARBU factor",
    "products.selectFactor": "Select factor…",
    "products.addIva": "Add VAT…",
    "products.factoryTaxCharge": "Factory tax charge (assumed)",
    "products.noFactoryCharge": "No factory charge",
    "products.factoryTaxAssumed": "Factory tax is assumed in the price — affects total calculation.",
    "products.factoryTaxNotAssumed": "Factory charge without assumed tax.",
    // Commercial value
    "products.commercialPrice": "Commercial price",
    "products.basePriceNoTax": "Base price (no taxes)",
    "products.estimatedSalePrice": "Estimated sale price",
    "products.basePriceLine": "Base price",
    "products.netPrice": "Net price",
    "products.baseForIva": "Base for VAT",
    "products.factoryAssumedTax": "Factory assumed tax",
    "products.totalIva": "Total VAT",
    "products.totalOtherTaxes": "Total other taxes",

    // shell
    "shell.navigation": "Navigation",
    "shell.panel": "Panel",
    "shell.sessions": "Sessions",
    "shell.stations": "Stations",
    "shell.products": "Products",
    "shell.clients": "Clients",
    "shell.reports": "Reports",
    "shell.logout": "Log out",
    "shell.liveLabel": "Live",
    "shell.activeSession": "Active session",
    "shell.sync": "Sync",

    // cart
    "cart.item": "item",
    "cart.items": "items",
    "cart.selectProducts": "Select products",

    // report
    "report.finalReport": "Final report",
    "report.loading": "Loading report…",
    "report.downloadPdf": "Download PDF",
    "report.grossIncome": "Gross income",
    "report.orders": "Orders",
    "report.avgTicket": "Avg ticket",
    "report.cashDiff": "Cash difference",
    "report.balanced": "Balanced",
    "report.allStandsBalanced": "All stands balanced",
    "report.standsWithDiff": "Stands with difference",
    "report.paymentMethods": "Payment methods",
    "report.distribution": "Distribution of total",
    "report.cash": "Cash",
    "report.card": "Card",
    "report.sinpeMobile": "SINPE Mobile",
    "report.standPerformance": "Stand performance",
    "report.productsTable": "Products sold",
    "report.units": "Units",
    "report.revenue": "Revenue",
    "report.total": "Total",
    "report.noProductData": "No product data.",
    "report.noStandData": "No stand data.",
    "report.print": "Print",
    "report.csv": "CSV",

    // assignments
    "assignments.title": "Active assignments",
    "assignments.count": "{n} assignment(s) in progress",
    "assignments.newAssignment": "New assignment",
    "assignments.loading": "Loading assignments…",
    "assignments.noActive": "No active assignments",
    "assignments.station": "Station: {id}",
    "assignments.start": "Start: {time}",
    "assignments.finish": "Finish",
    "assignments.session": "Session",
    "assignments.seller": "Seller",
    "assignments.role": "Role",
    "assignments.cashier": "Cashier",
    "assignments.supervisor": "Supervisor",
    "assignments.assigning": "Assigning…",
    "assignments.create": "Create assignment",

    // puestos
    "puestos.title": "Stations",
    "puestos.subtitle": "{active} active · {total} total",
    "puestos.newStation": "New station",
    "puestos.all": "All",
    "puestos.stand": "Stand",
    "puestos.restaurant": "Restaurant",
    "puestos.onlyActive": "Active only",
    "puestos.addTerminal": "Add terminal",
    "puestos.terminals": "Terminals",

    // mobile dashboard
    "mobile.panel": "Manager panel",
    "mobile.orders": "Orders",
    "mobile.ticket": "Ticket",
    "mobile.stations": "Stations",
    "mobile.cashiers": "Cashiers",
    "mobile.sessionSales": "Session sales",
    "mobile.live": "Live",
    "mobile.summary": "Summary",
    "mobile.stationsTab": "Stations",
    "mobile.topTab": "Top",
    "mobile.lastSales": "Latest sales",
    "mobile.liveFeed": "Real-time feed",
    "mobile.noSales": "No sales yet.",
    "mobile.noCashier": "No cashier",
    "mobile.stationOrders": "{n} orders",
    "mobile.noProductData": "No product data.",
    "mobile.noActiveStations": "No active stations.",
    "mobile.timeAgo": "{time} ago",

    // session config
    "session.title": "Configure session",
    "session.subtitle": "Create a new match or regular operating day and assign cashiers to each stand.",
    "session.activating": "Activating…",
    "session.activate": "Activate session",
    "session.requiredSteps": "To activate, complete",
    "session.selectBranches": "Select at least one stand",
    "session.assignMembers": "Assign a cashier to each stand",
    "session.selectDate": "Select date and time",
    "session.selectProducts": "Select at least one product",
    "session.tabMatch": "Match details",
    "session.tabStations": "Stations & assignments",
    "session.tabInventory": "Initial inventory",
    "session.sessionInfo": "Session information",
    "session.sessionInfoDesc": "Cashiers will see this context when opening a shift.",
    "session.sessionType": "Session type",
    "session.match": "Match",
    "session.matchDesc": "Stadium sales",
    "session.regular": "Regular day",
    "session.regularDesc": "Restaurant operation",
    "session.rivalTeam": "Rival team",
    "session.matchTime": "Match time",
    "session.date": "Date",
    "session.mainBranch": "Main branch",
    "session.noBranch": "No branch",
    "session.preview": "Preview",
    "session.previewDesc": "How cashiers will see it",
    "session.vsRival": "vs Rival",
    "session.regularOp": "Regular operation",
    "session.noDate": "No date",
    "session.stations": "Stations",
    "session.assigned": "Assigned",
    "session.selectStations": "Select stations",
    "session.activeForSession": "{n} active stations for this session",
    "session.noBranches": "No branches available.",
    "session.assignments": "Assignments",
    "session.assignedCount": "{n}/{total} stations with assigned cashier",
    "session.cashier": "Cashier",
    "session.unassigned": "Unassigned",
    "session.role": "Role",
    "session.select": "Select…",
    "session.inventoryTitle": "Initial inventory per station",
    "session.inventoryDesc": "Quantity of each product to deliver at shift opening",
    "session.selectFirst": "(Select stations first)",
    "session.total": "Total",
    "session.noActiveProducts": "No active products.",
    "session.manageActiveSessions": "Manage active and closed sessions",
    "session.newSession": "New session",
    "session.allSessions": "All",
    "session.activeSessions": "Active",
    "session.closedSessions": "Closed",
    "session.noSessions": "No sessions yet",
    "session.createFirstSession": "Create your first session to start operations",
    "session.active": "Active",
    "session.startTime": "Start time",
    "session.endTime": "End time",
    "session.endSession": "End session",
    "session.confirmEnd": "Are you sure you want to end this session?",
    "session.confirmDelete": "Are you sure you want to delete this session?",

    // analytics
    "analytics.title": "ANALYTICS",
    "analytics.today": "Today",
    "analytics.week": "Week",
    "analytics.month": "Month",
    "analytics.season": "Season",
    "analytics.revenue": "REVENUE",
    "analytics.sales": "SALES",
    "analytics.topProduct": "TOP PRODUCT",
    "analytics.topContext": "TOP CONTEXT",
    "analytics.loading": "Loading...",
    "analytics.tabProducts": "🏆 Products",
    "analytics.tabSessions": "📅 Sessions",
    "analytics.tabVendors": "👤 Vendors",
    "analytics.tabContext": "📍 Context",
    "analytics.colProduct": "PRODUCT",
    "analytics.colUnits": "UNITS",
    "analytics.colRevenue": "REVENUE",
    "analytics.colVolume": "VOLUME",
    "analytics.colSession": "SESSION",
    "analytics.colType": "TYPE",
    "analytics.colDate": "DATE",
    "analytics.colSales": "SALES",
    "analytics.colStatus": "STATUS",
    "analytics.colVendor": "VENDOR",
    "analytics.colTransactions": "TRANSACTIONS",
    "analytics.colAvgTicket": "AVG TICKET",
    "analytics.colFavPayment": "FAV PAYMENT",
    "analytics.statusClosed": "Closed",
    "analytics.statusActive": "Active",
    "analytics.salesCount": "{n} sales",
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem("language") as Language | null;
    if (saved === "en" || saved === "es") return saved;
    return navigator.language.toLowerCase().startsWith("es") ? "es" : "en";
  });

  const setLanguage = (lang: Language) => {
    localStorage.setItem("language", lang);
    setLanguageState(lang);
  };

  const t = (key: string, params?: Record<string, string | number>): string => {
    let text = translations[language][key] ?? key;
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        text = text.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
      });
    }
    return text;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage(): LanguageContextValue {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
